/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Member;

import Account.ViewAccounts;
import Account.CreateNewAccount;
import ConnectionProvider.ConnectionProvider;
import Home.Home;
import MemberInventory.Issuetomember;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ViewMember extends javax.swing.JFrame {

    /**
     * Creates new form ViewMember
     */
    public ViewMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonViewmember = new javax.swing.JButton();
        jButtonAddmember = new javax.swing.JButton();
        jButtonIssueinventory = new javax.swing.JButton();
        jButtonCreateaccount = new javax.swing.JButton();
        jButtonViewaccounts = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMember = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabelPersonalDetails = new javax.swing.JLabel();
        jLabelFullName = new javax.swing.JLabel();
        jTextFieldFullName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldContactNo = new javax.swing.JTextField();
        jTextFieldNationality = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxHousewife = new javax.swing.JCheckBox();
        jCheckBoxFarmer = new javax.swing.JCheckBox();
        jCheckBoxStudent = new javax.swing.JCheckBox();
        jCheckBoxGJH = new javax.swing.JCheckBox();
        jCheckBoxPJH = new javax.swing.JCheckBox();
        jCheckBoxBusiness = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldFatherName = new javax.swing.JTextField();
        jTextFieldMotherName = new javax.swing.JTextField();
        jTextFieldGrandFatherName = new javax.swing.JTextField();
        jTextFieldGrandMotherName = new javax.swing.JTextField();
        jTextFieldSpouseName = new javax.swing.JTextField();
        jCheckBoxOther = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jRadioButtonCitizenship = new javax.swing.JRadioButton();
        jRadioButtonBirthRegistration = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldCitizenshipno = new javax.swing.JTextField();
        jTextFieldIssuedBy = new javax.swing.JTextField();
        jTextFieldIssuedPlace = new javax.swing.JTextField();
        jTextFieldBirthRestrationNo = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCance = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldDOB = new javax.swing.JTextField();
        jTextFieldIssueddate = new javax.swing.JTextField();
        jLabelMember_id = new javax.swing.JLabel();
        jTextFieldMember_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonViewmember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewmember.setText("View Members");
        jButtonViewmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewmemberActionPerformed(evt);
            }
        });

        jButtonAddmember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddmember.setText("Add New Member");
        jButtonAddmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddmemberActionPerformed(evt);
            }
        });

        jButtonIssueinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonIssueinventory.setText("Issue Inventory");
        jButtonIssueinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIssueinventoryActionPerformed(evt);
            }
        });

        jButtonCreateaccount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateaccount.setText("Create Account");
        jButtonCreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateaccountActionPerformed(evt);
            }
        });

        jButtonViewaccounts.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewaccounts.setText("View Accounts");
        jButtonViewaccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewaccountsActionPerformed(evt);
            }
        });

        jButtonHome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTableMember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTableMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Id", "Full Name", "Gender", "Nationality", "Contact No", "Date of Birth", "Address", "Occupation", "Father Name", "Mother Name", "Spouse Name", "Grand Father Name", "Grand Mother Name", "Document Type", "Citizenship Number", "Birth Registration Number", "Issued By", "Issued Place", "Issued Date", "Member Registration Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMember.setRowHeight(30);
        jTableMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMember);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1361, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.Color.lightGray);

        jLabelPersonalDetails.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelPersonalDetails.setText("Personal Details:");

        jLabelFullName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelFullName.setText("Full Name:");

        jTextFieldFullName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFullNameActionPerformed(evt);
            }
        });
        jTextFieldFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFullNameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Gender:");

        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonFemale.setText("Female");

        buttonGroup1.add(jRadioButtonOther);
        jRadioButtonOther.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonOther.setText("Other");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Contact No.:");

        jTextFieldContactNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactNoActionPerformed(evt);
            }
        });
        jTextFieldContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldContactNoKeyPressed(evt);
            }
        });

        jTextFieldNationality.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNationalityActionPerformed(evt);
            }
        });
        jTextFieldNationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNationalityKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Nationality:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Address:");

        jTextFieldAddress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Occupation:");

        buttonGroup2.add(jCheckBoxHousewife);
        jCheckBoxHousewife.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxHousewife.setText("Housewife");

        buttonGroup2.add(jCheckBoxFarmer);
        jCheckBoxFarmer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxFarmer.setText("Farmer");
        jCheckBoxFarmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFarmerActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCheckBoxStudent);
        jCheckBoxStudent.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxStudent.setText("Student");

        buttonGroup2.add(jCheckBoxGJH);
        jCheckBoxGJH.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxGJH.setText("Government Job Holder");

        buttonGroup2.add(jCheckBoxPJH);
        jCheckBoxPJH.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxPJH.setText("Private Job Holder");

        buttonGroup2.add(jCheckBoxBusiness);
        jCheckBoxBusiness.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxBusiness.setText("Business Person");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("Date of Birth");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("Family Details:");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("Father's Name:");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setText("Mother's Name:");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setText("Grand Father's Name:");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setText("Grand Mother's Name:");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel17.setText("Spouse Name:");

        jTextFieldFatherName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFatherNameActionPerformed(evt);
            }
        });
        jTextFieldFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFatherNameKeyPressed(evt);
            }
        });

        jTextFieldMotherName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMotherNameActionPerformed(evt);
            }
        });
        jTextFieldMotherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMotherNameKeyPressed(evt);
            }
        });

        jTextFieldGrandFatherName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldGrandFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldGrandFatherNameKeyPressed(evt);
            }
        });

        jTextFieldGrandMotherName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldGrandMotherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldGrandMotherNameKeyPressed(evt);
            }
        });

        jTextFieldSpouseName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldSpouseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSpouseNameActionPerformed(evt);
            }
        });
        jTextFieldSpouseName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSpouseNameKeyPressed(evt);
            }
        });

        buttonGroup2.add(jCheckBoxOther);
        jCheckBoxOther.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxOther.setText("Others");
        jCheckBoxOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOtherActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Document Type:");

        buttonGroup3.add(jRadioButtonCitizenship);
        jRadioButtonCitizenship.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonCitizenship.setText("Citizenship");
        jRadioButtonCitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCitizenshipActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonBirthRegistration);
        jRadioButtonBirthRegistration.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonBirthRegistration.setText("Birth Registration");
        jRadioButtonBirthRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBirthRegistrationActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel18.setText("Citizenship No.:");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setText("Birth Registration no.:");

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setText("Issued By:");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel21.setText("Issued Place:");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel22.setText("Issued Date:");

        jTextFieldCitizenshipno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCitizenshipno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCitizenshipnoActionPerformed(evt);
            }
        });
        jTextFieldCitizenshipno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCitizenshipnoKeyPressed(evt);
            }
        });

        jTextFieldIssuedBy.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldIssuedBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIssuedByKeyPressed(evt);
            }
        });

        jTextFieldIssuedPlace.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldIssuedPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIssuedPlaceActionPerformed(evt);
            }
        });
        jTextFieldIssuedPlace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldIssuedPlaceKeyPressed(evt);
            }
        });

        jTextFieldBirthRestrationNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldBirthRestrationNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBirthRestrationNoKeyPressed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jButtonUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonUpdateKeyPressed(evt);
            }
        });

        jButtonCance.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCance.setText("Clear");
        jButtonCance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanceActionPerformed(evt);
            }
        });

        jButtonEdit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jTextFieldDOB.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelMember_id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelMember_id.setText("Member_id");

        jTextFieldMember_id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelFullName)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabelMember_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(73, 73, 73))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(78, 78, 78))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel13))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldGrandMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldSpouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldGrandFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButtonEdit)
                                        .addGap(83, 83, 83)
                                        .addComponent(jButtonUpdate)
                                        .addGap(112, 112, 112)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jButtonCance)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(45, 45, 45)
                                                        .addComponent(jRadioButtonMale))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(34, 34, 34)
                                                        .addComponent(jRadioButtonCitizenship)))
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jRadioButtonFemale)
                                                        .addGap(119, 119, 119)
                                                        .addComponent(jRadioButtonOther))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(41, 41, 41)
                                                        .addComponent(jRadioButtonBirthRegistration)))))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(154, 154, 154)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldCitizenshipno, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextFieldIssuedPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jTextFieldIssueddate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addComponent(jLabel19)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextFieldBirthRestrationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(204, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jCheckBoxHousewife, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(58, 58, 58)
                                                .addComponent(jCheckBoxFarmer)
                                                .addGap(30, 30, 30)
                                                .addComponent(jCheckBoxStudent)))
                                        .addGap(27, 27, 27)
                                        .addComponent(jCheckBoxGJH)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxPJH)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCheckBoxBusiness)
                                        .addGap(26, 26, 26)
                                        .addComponent(jCheckBoxOther))
                                    .addComponent(jTextFieldMember_id, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(jLabelPersonalDetails)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPersonalDetails))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMember_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldMember_id, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFullName)
                    .addComponent(jTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale)
                    .addComponent(jRadioButtonOther)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBoxHousewife)
                    .addComponent(jCheckBoxFarmer)
                    .addComponent(jCheckBoxStudent)
                    .addComponent(jCheckBoxGJH)
                    .addComponent(jCheckBoxPJH)
                    .addComponent(jCheckBoxBusiness)
                    .addComponent(jCheckBoxOther))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jRadioButtonCitizenship)
                            .addComponent(jRadioButtonBirthRegistration)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCitizenshipno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jTextFieldBirthRestrationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jTextFieldMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jTextFieldSpouseName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(jTextFieldIssuedPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldGrandFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22)
                                            .addComponent(jTextFieldIssueddate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldGrandMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonCance)
                            .addComponent(jButtonEdit))
                        .addGap(29, 29, 29))))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIssueinventory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonViewaccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddmember, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonViewmember, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1637, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1895, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonViewmember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddmember)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonViewaccounts)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonCreateaccount)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonIssueinventory)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonClear)
                        .addGap(15, 15, 15)
                        .addComponent(jButtonHome)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setText("Pashupati Mahila Jibikoparjan Krishi Sahakari Sanstha");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setText("Members");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(729, 729, 729)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(601, 601, 601))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        jTextFieldAddress.setEditable(true);
        jTextFieldBirthRestrationNo.setEditable(true);
        jTextFieldCitizenshipno.setEditable(true);
        jTextFieldContactNo.setEditable(true);
        jTextFieldDOB.setEditable(true);
        jTextFieldFatherName.setEditable(true);
        jTextFieldFullName.setEditable(true);
        jTextFieldGrandFatherName.setEditable(true);
        jTextFieldGrandMotherName.setEditable(true);
        jTextFieldIssuedBy.setEditable(true);
        jTextFieldIssuedPlace.setEditable(true);
        jTextFieldIssueddate.setEditable(true);
        jTextFieldMotherName.setEditable(true);
        jTextFieldNationality.setEditable(true);
        jTextFieldSpouseName.setEditable(true);
        jTextFieldMember_id.setEditable(false);

    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonCanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanceActionPerformed
        // TODO add your handling code here:
        jTextFieldFullName.setText(null);
        jTextFieldAddress.setText(null);
        jTextFieldBirthRestrationNo.setText(null);
        jTextFieldCitizenshipno.setText(null);
        jTextFieldContactNo.setText(null);
        jTextFieldFatherName.setText(null);
        jTextFieldMotherName.setText(null);
        jTextFieldGrandFatherName.setText(null);
        jTextFieldSpouseName.setText(null);
        jTextFieldIssuedBy.setText(null);
        jTextFieldIssuedPlace.setText(null);
        jTextFieldNationality.setText(null);
        jTextFieldDOB.setText(null);
        jTextFieldIssueddate.setText(null);
        jTextFieldMember_id.setText(null);

    }//GEN-LAST:event_jButtonCanceActionPerformed

    private void jButtonUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonUpdateKeyPressed

    }//GEN-LAST:event_jButtonUpdateKeyPressed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        jRadioButtonMale.setActionCommand("Male");
        jRadioButtonFemale.setActionCommand("Female");
        jRadioButtonOther.setActionCommand("Other");
        jRadioButtonBirthRegistration.setActionCommand("Birth Registration");
        jRadioButtonCitizenship.setActionCommand("Citizenship");
        jCheckBoxBusiness.setActionCommand("Business Person");
        jCheckBoxFarmer.setActionCommand("Farmer");
        jCheckBoxGJH.setActionCommand("Government Job Holder");
        jCheckBoxHousewife.setActionCommand("Housewife");
        jCheckBoxOther.setActionCommand("Other");
        jCheckBoxPJH.setActionCommand("Private Job Holder");
        jCheckBoxStudent.setActionCommand("Student");
        int Member_id=Integer.parseInt(jTextFieldMember_id.getText());
        String Full_name=jTextFieldFullName.getText();
        String Gender=buttonGroup1.getSelection().getActionCommand();
        String Nationality=jTextFieldNationality.getText();
        String DOB=jTextFieldDOB.getText();
        String Contact_no=jTextFieldContactNo.getText();
        String Address=jTextFieldAddress.getText();
        String Occupation=buttonGroup3.getSelection().getActionCommand();
        String Father_name=jTextFieldFatherName.getText();
        String Mother_name=jTextFieldGrandMotherName.getText();
        String Spouse_name=jTextFieldSpouseName.getText();
        String Grand_father_name=jTextFieldGrandFatherName.getText();
        String Grand_mother_name=jTextFieldGrandMotherName.getText();
        String Document_type=buttonGroup2.getSelection().getActionCommand();
        String Citizenship_no=jTextFieldContactNo.getText();
        String Birth_registration_no=jTextFieldBirthRestrationNo.getText();
        String Issued_by=jTextFieldIssuedBy.getText();
        String Issued_place=jTextFieldIssuedPlace.getText();
        String Issued_date=jTextFieldIssueddate.getText();
        String url="jdbc:mysql://localhost:3306/cooperativemanagementsystem";
        String uname="root";
        String pwd="";
        ResultSet rs;
        try{
            //step1: Load the database driver
            Class.forName("com.mysql.jdbc.Driver");
            //step2: connect to the database
            Connection con=DriverManager.getConnection(url,uname,pwd);
            //step3: create sql query and execute it
            String sql="update member set Full_name=?,Gender=?,Nationality=?, Contact_no=?,DOB=?, Address=?,"
            + "Occupation=?,Father_name=?,Mother_name=?, Spouse_name=?,Grand_father_name=?,"
            + "Grand_mother_name=?,Document_type=?,Citizenship_no=?,Birth_registration_no=?,"
            + "Issued_by=?,Issued_place=?,Issued_date=? where Member_id=?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1,Full_name);
            st.setString(2,Gender);
            st.setString(3, Nationality);
            st.setString(4, Contact_no);
            st.setString(5,DOB);
            st.setString(6,Address);
            st.setString(7,Occupation);
            st.setString(8, Father_name);
            st.setString(9, Mother_name);
            st.setString(10,Spouse_name);
            st.setString(11, Grand_father_name);
            st.setString(12,Grand_mother_name);
            st.setString(13, Document_type);
            st.setString(14,Citizenship_no);
            st.setString(15, Birth_registration_no);
            st.setString(16, Issued_by);
            st.setString(17, Issued_place);
            st.setString(18,Issued_date);
            st.setInt(19,Member_id);
            st.execute();
            //step4: close the connection
            con.close();
            JOptionPane.showMessageDialog(rootPane, "Sucessfully Updated of member with Member id="+Member_id);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        try {
            jTextFieldFullName.setText(null);
            jTextFieldAddress.setText(null);
            jTextFieldBirthRestrationNo.setText(null);
            jTextFieldCitizenshipno.setText(null);
            jTextFieldContactNo.setText(null);
            jTextFieldFatherName.setText(null);
            jTextFieldMotherName.setText(null);
            jTextFieldGrandFatherName.setText(null);
            jTextFieldSpouseName.setText(null);
            jTextFieldIssuedBy.setText(null);
            jTextFieldIssuedPlace.setText(null);
            jTextFieldNationality.setText(null);
            jTextFieldDOB.setText(null);
            jTextFieldIssueddate.setText(null);
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldBirthRestrationNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBirthRestrationNoKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isDigit(c)||evt.getKeyCode()==KeyEvent.VK_SUBTRACT||evt.getKeyCode()==KeyEvent.VK_DIVIDE||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldBirthRestrationNo.setEditable(true);
            }
            else{
                jTextFieldBirthRestrationNo.setEditable(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldBirthRestrationNoKeyPressed

    private void jTextFieldIssuedPlaceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIssuedPlaceKeyPressed
        // TODO add your handling code here:
        //        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            //            jDateChooserIssuedDate.requestFocus();
            //        }
        //        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            //            jDateChooserDOB.requestFocus();
            //        }
        //        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            //            jDateChooserDOB.requestFocus();
            //        }
        //        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            //            jTextFieldIssuedBy.requestFocus();
            //        }
    }//GEN-LAST:event_jTextFieldIssuedPlaceKeyPressed

    private void jTextFieldIssuedPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIssuedPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIssuedPlaceActionPerformed

    private void jTextFieldIssuedByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIssuedByKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldIssuedPlace.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldIssuedPlace.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldIssuedPlace.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldCitizenshipno.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldIssuedByKeyPressed

    private void jTextFieldCitizenshipnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCitizenshipnoKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isDigit(c)||evt.getKeyCode()==KeyEvent.VK_SUBTRACT||evt.getKeyCode()==KeyEvent.VK_DIVIDE||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldCitizenshipno.setEditable(true);
            }
            else{
                jTextFieldCitizenshipno.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldIssuedBy.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldBirthRestrationNo.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldIssuedBy.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldGrandMotherName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldCitizenshipnoKeyPressed

    private void jTextFieldCitizenshipnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCitizenshipnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCitizenshipnoActionPerformed

    private void jRadioButtonBirthRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBirthRegistrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBirthRegistrationActionPerformed

    private void jRadioButtonCitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCitizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCitizenshipActionPerformed

    private void jCheckBoxOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxOtherActionPerformed

    private void jTextFieldSpouseNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSpouseNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldSpouseName.setEditable(true);
            }
            else{
                jTextFieldSpouseName.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldGrandFatherName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldIssuedBy.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldGrandFatherName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldMotherName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldSpouseNameKeyPressed

    private void jTextFieldSpouseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSpouseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSpouseNameActionPerformed

    private void jTextFieldGrandMotherNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGrandMotherNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldGrandMotherName.setEditable(true);
            }
            else{
                jTextFieldGrandMotherName.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldCitizenshipno.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldCitizenshipno.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldCitizenshipno.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldGrandFatherName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldGrandMotherNameKeyPressed

    private void jTextFieldGrandFatherNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGrandFatherNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldGrandFatherName.setEditable(true);
            }
            else{
                jTextFieldGrandFatherName.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldGrandMotherName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldIssuedPlace.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldGrandMotherName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldSpouseName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldGrandFatherNameKeyPressed

    private void jTextFieldMotherNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMotherNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldMotherName.setEditable(true);
            }
            else{
                jTextFieldMotherName.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldSpouseName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldCitizenshipno.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldSpouseName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldFatherName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldMotherNameKeyPressed

    private void jTextFieldMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMotherNameActionPerformed

    private void jTextFieldFatherNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFatherNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldFatherName.setEditable(true);
            }
            else{
                jTextFieldFatherName.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldMotherName.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jRadioButtonCitizenship.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldMotherName.requestFocus();
        }

    }//GEN-LAST:event_jTextFieldFatherNameKeyPressed

    private void jTextFieldFatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFatherNameActionPerformed

    private void jCheckBoxFarmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFarmerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFarmerActionPerformed

    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldDOB.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldDOB.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldDOB.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldAddress.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldAddressKeyPressed

    private void jTextFieldNationalityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNationalityKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldNationality.setEditable(true);
            }
            else{
                jTextFieldNationality.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldAddress.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldAddress.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldAddress.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldContactNo.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldNationalityKeyPressed

    private void jTextFieldNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNationalityActionPerformed

    private void jTextFieldContactNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContactNoKeyPressed
        // TODO add your handling code here:

        char c=evt.getKeyChar();
        try {
            if (Character.isDigit(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldContactNo.setEditable(true);
            }
            else{
                jTextFieldContactNo.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jTextFieldNationality.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldNationality.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldAddress.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_UP) {
            jTextFieldFullName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldContactNoKeyPressed

    private void jTextFieldContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactNoActionPerformed

    private void jRadioButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaleActionPerformed

    private void jTextFieldFullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFullNameKeyPressed
        // TO Transfer focus to another textfield
        char c=evt.getKeyChar();
        try {
            if (Character.isLetter(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_UP) {
                jTextFieldFullName.setEditable(true);
            }
            else{
                jTextFieldFullName.setEditable(false);
            }
        } catch (Exception e) {
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            jRadioButtonMale.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jRadioButtonMale.requestFocus();
        }
        else if (evt.getKeyCode()==KeyEvent.VK_DOWN) {
            jTextFieldContactNo.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldFullNameKeyPressed

    private void jTextFieldFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFullNameActionPerformed

    private void jTableMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMemberMouseClicked
        // TODO add your handling code here:
        String[] Member=new  String[20];

        if (evt.getClickCount() == 2) {
            int row = jTableMember.getSelectedRow();
            //                int column = jTableSupplier.getSelectedColumn();
            for (int column1 = 0; column1<20 ; column1++) {
                String data=String.valueOf(jTableMember.getValueAt(row, column1));
                Member[column1]=data;
            }
            jTextFieldMember_id.setText(Member[0]);
            jTextFieldFullName.setText(Member[1]);
            String Gender=Member[2];

            if(Gender=="Male"){
                jRadioButtonMale.setSelected(true);
            }
            else if (Gender=="Female") {
                jRadioButtonFemale.setSelected(true);
            } else {
                jRadioButtonOther.setSelected(true);
            }

            jTextFieldNationality.setText(Member[3]);
            jTextFieldContactNo.setText(Member[4]);
            jTextFieldDOB.setText(Member[5]);
            jTextFieldAddress.setText(Member[6]);
            String Occupation=Member[7];
            if (Occupation=="Private Job Holder") {
                jCheckBoxPJH.setSelected(true);
            }
            else if (Occupation=="Student") {
                jCheckBoxStudent.setSelected(true);
            }
            else if (Occupation=="Housewife") {
                jCheckBoxHousewife.setSelected(true);
            }
            else if (Occupation=="Farmer") {
                jCheckBoxFarmer.setSelected(true);
            }
            else if (Occupation=="Government Job Holder") {
                jCheckBoxGJH.setSelected(true);
            }
            else if (Occupation=="Business Person") {
                jCheckBoxBusiness.setSelected(true);
            }
            else if (Occupation=="Other") {
                jCheckBoxOther.setSelected(true);
            }
            else{
                jCheckBoxHousewife.setSelected(true);
            }
            jTextFieldFatherName.setText(Member[8]);
            jTextFieldMotherName.setText(Member[9]);
            jTextFieldSpouseName.setText(Member[10]);
            jTextFieldGrandFatherName.setText(Member[11]);
            jTextFieldGrandMotherName.setText(Member[12]);
            String Document_type=Member[13];
            if(Document_type=="Citizenship"){
                jRadioButtonCitizenship.setSelected(true);
            }
            else {
                jRadioButtonBirthRegistration.setSelected(true);
            }
            jTextFieldCitizenshipno.setText(Member[14]);
            jTextFieldBirthRestrationNo.setText(Member[15]);
            jTextFieldIssuedBy.setText(Member[16]);
            jTextFieldIssuedPlace.setText(Member[17]);
            jTextFieldIssueddate.setText(Member[18]);
            // you can play more here to get that cell value and all
        }
        jTextFieldAddress.setEditable(false);
        jTextFieldBirthRestrationNo.setEditable(false);
        jTextFieldCitizenshipno.setEditable(false);
        jTextFieldContactNo.setEditable(false);
        jTextFieldDOB.setEditable(false);
        jTextFieldFatherName.setEditable(false);
        jTextFieldFullName.setEditable(false);
        jTextFieldGrandFatherName.setEditable(false);
        jTextFieldGrandMotherName.setEditable(false);
        jTextFieldIssuedBy.setEditable(false);
        jTextFieldIssuedPlace.setEditable(false);
        jTextFieldIssueddate.setEditable(false);
        jTextFieldMotherName.setEditable(false);
        jTextFieldNationality.setEditable(false);
        jTextFieldSpouseName.setEditable(false);
        jTextFieldMember_id.setEditable(false);
    }//GEN-LAST:event_jTableMemberMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTableMember.setModel(new DefaultTableModel(null,new String [] {
            "Member ID", "Full Name", "Gender", "Nationality","Contact No",
            "Date of Birth","Address","Occupation"
            ,"Father Name","Mother Name","Spouse Name","Grand Father Name",
            "Grand Mother Name","Document Type","Citizenship Number",
            "Birth Registration Number","Issued By","Issued Place","Issued Date"
        }));
        jTextFieldFullName.setText(null);
        jTextFieldAddress.setText(null);
        jTextFieldBirthRestrationNo.setText(null);
        jTextFieldCitizenshipno.setText(null);
        jTextFieldContactNo.setText(null);
        jTextFieldFatherName.setText(null);
        jTextFieldMotherName.setText(null);
        jTextFieldGrandFatherName.setText(null);
        jTextFieldSpouseName.setText(null);
        jTextFieldIssuedBy.setText(null);
        jTextFieldIssuedPlace.setText(null);
        jTextFieldNationality.setText(null);
        jTextFieldDOB.setText(null);
        jTextFieldIssueddate.setText(null);
        jTextFieldMember_id.setText(null);

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonViewaccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewaccountsActionPerformed
        // TODO add your handling code here:
        new ViewAccounts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewaccountsActionPerformed

    private void jButtonCreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateaccountActionPerformed
        // TODO add your handling code here:
        new CreateNewAccount().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateaccountActionPerformed

    private void jButtonIssueinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIssueinventoryActionPerformed
        // TODO add your handling code here:
        new Issuetomember().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonIssueinventoryActionPerformed

    private void jButtonAddmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddmemberActionPerformed
        // TODO add your handling code here:
        new Addmember().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonAddmemberActionPerformed

    private void jButtonViewmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewmemberActionPerformed
        //clear the table first         
        jTableMember.setModel(new DefaultTableModel(null,new String [] {
            "Member ID", "Full Name", "Gender", "Nationality","Contact No",
            "Date of Birth","Address","Occupation"
            ,"Father Name","Mother Name","Spouse Name","Grand Father Name",
            "Grand Mother Name","Document Type","Citizenship Number",
            "Birth Registration Number","Issued By","Issued Place","Issued Date"
        }));
       Connection con= ConnectionProvider.getCon();
        ResultSet rs;
        try{

            //step3: create sql query and execute it
            String sql="select * from member";
            PreparedStatement st=con.prepareStatement(sql);
            rs=st.executeQuery();
            while (rs.next()) {

                String Member_id=String.valueOf(rs.getInt("Member_id"));
                String Full_name=rs.getString("Full_name");
                String Gender=rs.getString("Gender");
                String Nationality=rs.getString("Nationality");
                SimpleDateFormat SDF=new SimpleDateFormat("yyyy-MM-dd");
                String DOB=String.valueOf(rs.getDate("DOB"));
                String Contact_no=rs.getString("Contact_no");
                String Address=rs.getString("Address");
                String Occupation=rs.getString("Occupation");
                String Father_name=rs.getString("Father_name");
                String Mother_name=rs.getString("Mother_name");
                String Spouse_name=rs.getString("Spouse_name");
                String Grand_father_name=rs.getString("Grand_father_name");
                String Grand_mother_name=rs.getString("Grand_mother_name");
                String Document_type=rs.getString("Document_type");
                String Citizenship_no=rs.getString("Citizenship_no");
                String Birth_registration_no=rs.getString("Birth_registration_no");
                String Issued_by=rs.getString("Issued_by");
                String Issued_place=rs.getString("Issued_place");
                String Issued_date=String.valueOf(rs.getDate("Issued_date"));
                String Member_issued_date=String.valueOf(rs.getDate("Member_registration_date"));
                String table_data[]={Member_id,Full_name,Gender,Nationality,Contact_no,DOB,
                    Address,Occupation,Father_name,Mother_name,Spouse_name,Grand_father_name,Grand_mother_name,
                    Document_type,Citizenship_no,Birth_registration_no ,
                    Issued_by,Issued_place,Issued_date,Member_issued_date};
                DefaultTableModel tablemodel=(DefaultTableModel)jTableMember.getModel();
                tablemodel.addRow(table_data);
            }
            //step4: close the connection
            con.close();
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        jTextFieldAddress.setEditable(false);
        jTextFieldBirthRestrationNo.setEditable(false);
        jTextFieldCitizenshipno.setEditable(false);
        jTextFieldContactNo.setEditable(false);
        jTextFieldDOB.setEditable(false);
        jTextFieldFatherName.setEditable(false);
        jTextFieldFullName.setEditable(false);
        jTextFieldGrandFatherName.setEditable(false);
        jTextFieldGrandMotherName.setEditable(false);
        jTextFieldIssuedBy.setEditable(false);
        jTextFieldIssuedPlace.setEditable(false);
        jTextFieldIssueddate.setEditable(false);
        jTextFieldMotherName.setEditable(false);
        jTextFieldNationality.setEditable(false);
        jTextFieldSpouseName.setEditable(false);
    }//GEN-LAST:event_jButtonViewmemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonAddmember;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCance;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCreateaccount;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonIssueinventory;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonViewaccounts;
    private javax.swing.JButton jButtonViewmember;
    private javax.swing.JCheckBox jCheckBoxBusiness;
    private javax.swing.JCheckBox jCheckBoxFarmer;
    private javax.swing.JCheckBox jCheckBoxGJH;
    private javax.swing.JCheckBox jCheckBoxHousewife;
    private javax.swing.JCheckBox jCheckBoxOther;
    private javax.swing.JCheckBox jCheckBoxPJH;
    private javax.swing.JCheckBox jCheckBoxStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelMember_id;
    private javax.swing.JLabel jLabelPersonalDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonBirthRegistration;
    private javax.swing.JRadioButton jRadioButtonCitizenship;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMember;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBirthRestrationNo;
    private javax.swing.JTextField jTextFieldCitizenshipno;
    private javax.swing.JTextField jTextFieldContactNo;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldFatherName;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldGrandFatherName;
    private javax.swing.JTextField jTextFieldGrandMotherName;
    private javax.swing.JTextField jTextFieldIssuedBy;
    private javax.swing.JTextField jTextFieldIssuedPlace;
    private javax.swing.JTextField jTextFieldIssueddate;
    private javax.swing.JTextField jTextFieldMember_id;
    private javax.swing.JTextField jTextFieldMotherName;
    private javax.swing.JTextField jTextFieldNationality;
    private javax.swing.JTextField jTextFieldSpouseName;
    // End of variables declaration//GEN-END:variables
}
