/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaction;

import Account.Balance;
import Account.ViewAccounts;
import ConnectionProvider.ConnectionProvider;
import Transaction.Deposit;
import Transaction.Withdraw;
import Home.Home;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTransferlabel1 = new javax.swing.JLabel();
        jTransfer = new javax.swing.JLabel();
        jSender = new javax.swing.JLabel();
        jAccountno = new javax.swing.JLabel();
        jAccountName = new javax.swing.JLabel();
        jMemberid = new javax.swing.JLabel();
        jAmount = new javax.swing.JLabel();
        jRemarks = new javax.swing.JLabel();
        jReceiver = new javax.swing.JLabel();
        jReceiverMemberid = new javax.swing.JLabel();
        jReceiverAccountName = new javax.swing.JLabel();
        jReceiverAccountnumber = new javax.swing.JLabel();
        jTextFieldAccountNumber = new javax.swing.JTextField();
        jTextFieldAccountName = new javax.swing.JTextField();
        jTextFieldMemberId = new javax.swing.JTextField();
        jTextFieldAmount = new javax.swing.JTextField();
        jTextFieldRemarks = new javax.swing.JTextField();
        jTextFieldReceivermemberid = new javax.swing.JTextField();
        jTextFieldReceiverAccountName = new javax.swing.JTextField();
        jTextFieldReceiveraccountno = new javax.swing.JTextField();
        jButtonProceed = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanelSideBar2 = new javax.swing.JPanel();
        jButtonViewBalance = new javax.swing.JButton();
        jButtonWithdraw = new javax.swing.JButton();
        jButtonDeposit = new javax.swing.JButton();
        jButtonTransfer = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jButtonhome = new javax.swing.JButton();
        jButtonviewaccounts = new javax.swing.JButton();
        jLabelTransactiontype = new javax.swing.JLabel();
        jCheckBoxWithdraw = new javax.swing.JCheckBox();
        jLabel2Transactiontype = new javax.swing.JLabel();
        jCheckBoxDeposit = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTransferlabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTransferlabel1.setText("Pashupati Mahila JibikoParjan Krishi Sahakari Sanstha");

        jTransfer.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTransfer.setText("Transfer");

        jSender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jSender.setText("Sender");

        jAccountno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jAccountno.setText("Account no:");

        jAccountName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jAccountName.setText("Account Name:");

        jMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMemberid.setText("Member id:");

        jAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jAmount.setText("Amount:");

        jRemarks.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRemarks.setText("Remarks:");

        jReceiver.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jReceiver.setText("Receiver:");

        jReceiverMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jReceiverMemberid.setText("Member id.:");

        jReceiverAccountName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jReceiverAccountName.setText("Account Name:");

        jReceiverAccountnumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jReceiverAccountnumber.setText("Account No.:");

        jTextFieldAccountNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountNumberActionPerformed(evt);
            }
        });
        jTextFieldAccountNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAccountNumberKeyPressed(evt);
            }
        });

        jTextFieldAccountName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAccountName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountNameActionPerformed(evt);
            }
        });

        jTextFieldMemberId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMemberIdActionPerformed(evt);
            }
        });

        jTextFieldAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountActionPerformed(evt);
            }
        });
        jTextFieldAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAmountKeyPressed(evt);
            }
        });

        jTextFieldRemarks.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldRemarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRemarksActionPerformed(evt);
            }
        });

        jTextFieldReceivermemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldReceivermemberid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReceivermemberidActionPerformed(evt);
            }
        });

        jTextFieldReceiverAccountName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldReceiveraccountno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldReceiveraccountno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldReceiveraccountnoKeyPressed(evt);
            }
        });

        jButtonProceed.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonExit.setText("Back");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonViewBalance.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewBalance.setText("View Balance");
        jButtonViewBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewBalanceActionPerformed(evt);
            }
        });

        jButtonWithdraw.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonWithdraw.setText("Withdraw");
        jButtonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWithdrawActionPerformed(evt);
            }
        });

        jButtonDeposit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonDeposit.setText("Deposit");
        jButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositActionPerformed(evt);
            }
        });

        jButtonTransfer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonTransfer.setText("Transfer");
        jButtonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferActionPerformed(evt);
            }
        });

        jButtonback.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        jButtonclear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonclear.setText("Clear");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jButtonhome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonhome.setText("Home");
        jButtonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhomeActionPerformed(evt);
            }
        });

        jButtonviewaccounts.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonviewaccounts.setText("View Accounts");
        jButtonviewaccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonviewaccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSideBar2Layout = new javax.swing.GroupLayout(jPanelSideBar2);
        jPanelSideBar2.setLayout(jPanelSideBar2Layout);
        jPanelSideBar2Layout.setHorizontalGroup(
            jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBar2Layout.createSequentialGroup()
                .addGroup(jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonback, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonhome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonViewBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButtonviewaccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanelSideBar2Layout.setVerticalGroup(
            jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBar2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jButtonTransfer)
                .addGap(27, 27, 27)
                .addComponent(jButtonWithdraw)
                .addGap(35, 35, 35)
                .addComponent(jButtonDeposit)
                .addGap(30, 30, 30)
                .addComponent(jButtonViewBalance)
                .addGap(20, 20, 20)
                .addComponent(jButtonviewaccounts)
                .addGap(20, 20, 20)
                .addComponent(jButtonclear)
                .addGap(20, 20, 20)
                .addComponent(jButtonhome)
                .addGap(20, 20, 20)
                .addComponent(jButtonback))
        );

        jLabelTransactiontype.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTransactiontype.setText("Transaction type: ");

        buttonGroup1.add(jCheckBoxWithdraw);
        jCheckBoxWithdraw.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxWithdraw.setSelected(true);
        jCheckBoxWithdraw.setText("Withdraw");

        jLabel2Transactiontype.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2Transactiontype.setText("Transaction type");

        buttonGroup2.add(jCheckBoxDeposit);
        jCheckBoxDeposit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCheckBoxDeposit.setSelected(true);
        jCheckBoxDeposit.setText("Deposit");
        jCheckBoxDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jTransferlabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanelSideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAccountno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonProceed)
                                .addGap(88, 88, 88)
                                .addComponent(jButtonClear)
                                .addGap(82, 82, 82)
                                .addComponent(jButtonExit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSender, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabelTransactiontype))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jReceiverAccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jReceiverAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jReceiverMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldReceiverAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldReceivermemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTransfer)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel2Transactiontype)
                                                    .addGap(0, 82, Short.MAX_VALUE))
                                                .addComponent(jTextFieldReceiveraccountno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxWithdraw)
                                    .addComponent(jCheckBoxDeposit))))))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTransferlabel1)
                .addGap(30, 30, 30)
                .addComponent(jTransfer)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTransactiontype)
                    .addComponent(jCheckBoxWithdraw))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAccountno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2Transactiontype)
                                    .addComponent(jCheckBoxDeposit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jReceiverAccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldReceiveraccountno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jReceiverAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldReceiverAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jReceiverMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldReceivermemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jPanelSideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonProceed)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonExit))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldAccountName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAccountNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountNameActionPerformed

    private void jTextFieldMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMemberIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMemberIdActionPerformed

    private void jTextFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountActionPerformed

    private void jTextFieldRemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRemarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRemarksActionPerformed

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
        // proceed button
        //Receiver
        jCheckBoxDeposit.setActionCommand("Deposit");
        int Receiver_account_no=Integer.parseInt(jTextFieldReceiveraccountno.getText());
        String Receiver_account_name=jTextFieldReceiverAccountName.getText();
        int Receiver_member_id=Integer.parseInt(jTextFieldReceivermemberid.getText());
        String Transaction_type2=buttonGroup2.getSelection().getActionCommand();
        //Sender
        jCheckBoxWithdraw.setActionCommand("Withdraw");
        Integer Member_id=Integer.parseInt(jTextFieldMemberId.getText());
        String Account_name=jTextFieldAccountName.getText();
        Integer Account_no=Integer.parseInt(jTextFieldAccountNumber.getText());
        int Amount=Integer.parseInt(jTextFieldAmount.getText());
        int Received_amount=Integer.parseInt(jTextFieldAmount.getText());
        String Remarks=jTextFieldRemarks.getText();
        String Transaction_type=buttonGroup1.getSelection().getActionCommand();
        Connection con= ConnectionProvider.getCon();
        ResultSet rs,rs1= null;
         
        try{
             con.setAutoCommit(false);
            //step3: create sql query and execute it
            String sql="insert into Transaction (Member_id,Account_no,Account_name,Transaction_type,Amount,Transacted_by,Remarks)values(?,?,?,?,?,?,?)";
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1, Member_id);
             st.setInt(2, Account_no);
            st.setString(3, Account_name);
           
            st.setString(4, Transaction_type);
             st.setInt(5,Amount);
            st.setString(6, "Amount Transferred to Account no. "+Receiver_account_no);

            
            
            st.setString(7,Remarks);
            st.execute();
            String sql2="select Balance from account where Account_no= "+Account_no;
            double balance=0;
            PreparedStatement st2=con.prepareStatement(sql2);
            rs=st2.executeQuery();
            while(rs.next()){
                balance=rs.getDouble("Balance");
            }
            balance=balance-Amount;
            st2.execute();
            String sql3="Update account set Balance=? where Account_no=?";
            PreparedStatement st3=con.prepareStatement(sql3);
            st3.setDouble(1, balance);
            st3.setInt(2, Account_no);
            st3.execute();
            //Receiver
            String sql4="insert into Transaction (Member_id,Account_no,Account_name,"
                    + "Transaction_type,Amount,Transacted_by,Remarks)"
                    + "values(?,?,?,?,?,?,?)";
            PreparedStatement st4=con.prepareStatement(sql4);
            st4.setInt(1, Receiver_member_id);
             st4.setInt(2, Receiver_account_no);
            st4.setString(3, Receiver_account_name);
            st4.setString(4, Transaction_type2);
            st4.setInt(5,Amount);
            st4.setString(6, "Amount Received from Account no."+Account_no);
            st4.setString(7,Remarks);
            st4.execute();
            String sql5="select Balance from account where Account_no="+Receiver_account_no;
            double balance2=0;
            PreparedStatement st5=con.prepareStatement(sql5);
            rs=st5.executeQuery();
            while(rs.next()){
                balance2=rs.getDouble("Balance");
            }
            balance2=balance2+Amount;
            st5.execute();
            String sql6="Update account set Balance=? where Account_no=?";
            PreparedStatement st6=con.prepareStatement(sql6);
            st6.setDouble(1, balance2);
            st6.setInt(2, Receiver_account_no);
            st6.execute();
            //step4: close the connection
            con.commit();
            con.close(); 
        JOptionPane.showMessageDialog(null,"Amount "+ Amount +" has been transferred from Account"
                + Account_no+ " to Account number"
                        + Account_no);
        }
        
        catch(Exception ex){
            try{
                con.rollback();
            }catch(Exception e){
                System.out.println(e);
            }
            System.out.println(ex);
        }
        try {
            jTextFieldAccountName.setText(null);
            jTextFieldAccountNumber.setText(null);
            jTextFieldAmount.setText(null);
            jTextFieldRemarks.setText(null);
            jTextFieldReceiveraccountno.setText(null);
            jTextFieldMemberId.setText(null);
             jTextFieldReceivermemberid.setText(null);
           jTextFieldReceiverAccountName.setText(null);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButtonProceedActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldAccountName.setText(null);
        jTextFieldAccountNumber.setText(null);
        jTextFieldAmount.setText(null);
        jTextFieldMemberId.setText(null);
        jTextFieldMemberId.setText(null);
        jTextFieldReceiverAccountName.setText(null);
        jTextFieldReceiveraccountno.setText(null);
        jTextFieldReceivermemberid.setText(null);
        jTextFieldRemarks.setText(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // Back
        new Home().setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextFieldAccountNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccountNumberKeyPressed
        // TODO add your handling code here:
             try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldAccountNumber.setEditable(true);
        }
        else{
            jTextFieldAccountNumber.setEditable(false);
        }
        } catch (Exception e) {
        }
       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        Integer Account_no=Integer.parseInt(jTextFieldAccountNumber.getText());
         Connection con= ConnectionProvider.getCon();
        ResultSet rs = null;
           try{
           //step3: create sql query and execute it for sender
           String sql="select Member_id,Account_name from account where Account_no="+Account_no;
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
           while(rs.next()){
               int Member_id=rs.getInt("Member_id");
               String Account_name=rs.getString("Account_name");
               jTextFieldAccountName.setText(Account_name);
               jTextFieldMemberId.setText(String.valueOf(Member_id));
           }
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
            System.out.println(ex);
            try {
               
           } catch (Exception e) {
           }
}
    }  
    }//GEN-LAST:event_jTextFieldAccountNumberKeyPressed

    private void jTextFieldReceiveraccountnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldReceiveraccountnoKeyPressed
        // TODO add your handling code here:
                     try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldReceiveraccountno.setEditable(true);
        }
        else{
            jTextFieldReceiveraccountno.setEditable(false);
        }
        } catch (Exception e) {
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        Integer Receiver_Account_no=Integer.parseInt(jTextFieldReceiveraccountno.getText());
        Connection con= ConnectionProvider.getCon();
        ResultSet rs = null;
           try{
           
           //step3: create sql query and execute it
           String sql="select Member_id,Account_name from account where Account_no="+Receiver_Account_no;
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
           while(rs.next()){
               int Member_id=rs.getInt("Member_id");
               String Account_name=rs.getString("Account_name");
               jTextFieldReceiverAccountName.setText(Account_name);
               jTextFieldReceivermemberid.setText(String.valueOf(Member_id));
           }
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
            System.out.println(ex);
}
    }  
    }//GEN-LAST:event_jTextFieldReceiveraccountnoKeyPressed

    private void jTextFieldAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountNumberActionPerformed

    private void jTextFieldAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAmountKeyPressed
        // TODO add your handling code here:
                     try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldAmount.setEditable(true);
        }
        else{
            jTextFieldAmount.setEditable(false);
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldAmountKeyPressed

    private void jButtonViewBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewBalanceActionPerformed
        // TODO add your handling code here:
        new Balance().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewBalanceActionPerformed

    private void jButtonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWithdrawActionPerformed
        // TODO add your handling code here:
        new Withdraw().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonWithdrawActionPerformed

    private void jButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositActionPerformed
        // TODO add your handling code here:
        new Deposit().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonDepositActionPerformed

    private void jButtonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferActionPerformed
        // TODO add your handling code here:
        new Transfer().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonTransferActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        Home HomeDemo=new Home();
        HomeDemo.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        jTextFieldAccountName.setText(null);
        jTextFieldAccountNumber.setText(null);
        jTextFieldAmount.setText(null);
        jTextFieldMemberId.setText(null);
        jTextFieldMemberId.setText(null);
        jTextFieldReceiverAccountName.setText(null);
        jTextFieldReceiveraccountno.setText(null);
        jTextFieldReceivermemberid.setText(null);
        jTextFieldRemarks.setText(null);
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jButtonviewaccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonviewaccountsActionPerformed
        // TODO add your handling code here:
        new ViewAccounts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonviewaccountsActionPerformed

    private void jCheckBoxDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDepositActionPerformed

    private void jButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonhomeActionPerformed

    private void jTextFieldReceivermemberidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReceivermemberidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReceivermemberidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jAccountName;
    private javax.swing.JLabel jAccountno;
    private javax.swing.JLabel jAmount;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDeposit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonTransfer;
    private javax.swing.JButton jButtonViewBalance;
    private javax.swing.JButton jButtonWithdraw;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtonhome;
    private javax.swing.JButton jButtonviewaccounts;
    private javax.swing.JCheckBox jCheckBoxDeposit;
    private javax.swing.JCheckBox jCheckBoxWithdraw;
    private javax.swing.JLabel jLabel2Transactiontype;
    private javax.swing.JLabel jLabelTransactiontype;
    private javax.swing.JLabel jMemberid;
    private javax.swing.JPanel jPanelSideBar2;
    private javax.swing.JLabel jReceiver;
    private javax.swing.JLabel jReceiverAccountName;
    private javax.swing.JLabel jReceiverAccountnumber;
    private javax.swing.JLabel jReceiverMemberid;
    private javax.swing.JLabel jRemarks;
    private javax.swing.JLabel jSender;
    private javax.swing.JTextField jTextFieldAccountName;
    private javax.swing.JTextField jTextFieldAccountNumber;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldMemberId;
    private javax.swing.JTextField jTextFieldReceiverAccountName;
    private javax.swing.JTextField jTextFieldReceiveraccountno;
    private javax.swing.JTextField jTextFieldReceivermemberid;
    private javax.swing.JTextField jTextFieldRemarks;
    private javax.swing.JLabel jTransfer;
    private javax.swing.JLabel jTransferlabel1;
    // End of variables declaration//GEN-END:variables
}
