/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MemberInventory;

import ConnectionProvider.ConnectionProvider;
import Home.Home;
import InventoryDetails.AddNewInventory;
import InventoryDetails.Createinventory;
import InventoryDetails.Inventory;
import InventoryDetails.ViewInventory;
import SupplierDetails.Supplier_inventory;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Issuetomember extends javax.swing.JFrame {

    /**
     * Creates new form Issue TO member
     */
    public Issuetomember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIssueHead = new javax.swing.JLabel();
        jIssue = new javax.swing.JLabel();
        jMemberid = new javax.swing.JLabel();
        jMemberName = new javax.swing.JLabel();
        jIneventroryId = new javax.swing.JLabel();
        jInventoryName = new javax.swing.JLabel();
        jQuantity = new javax.swing.JLabel();
        jRate = new javax.swing.JLabel();
        jTotal = new javax.swing.JLabel();
        jCash = new javax.swing.JLabel();
        jCredit = new javax.swing.JLabel();
        jTextFieldMemberid = new javax.swing.JTextField();
        jTextFieldMemberName = new javax.swing.JTextField();
        jTextFieldInventoryId = new javax.swing.JTextField();
        jTextFieldInventoryName = new javax.swing.JTextField();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldRate = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jTextFieldCash = new javax.swing.JTextField();
        jTextFieldCredit = new javax.swing.JTextField();
        jButtonProceed = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonViewinventory = new javax.swing.JButton();
        jButtonCreateinventory = new javax.swing.JButton();
        jButtonAddinventory = new javax.swing.JButton();
        jButtonViewmemberinventory = new javax.swing.JButton();
        jButtonViewsupplierinventory = new javax.swing.JButton();
        jButtonBack1 = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonIssuetomember = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIssueHead.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jIssueHead.setText("Inventory");

        jIssue.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jIssue.setText("Issue Inventory To Member");

        jMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMemberid.setText("Member ID");

        jMemberName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMemberName.setText("Member Name");

        jIneventroryId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jIneventroryId.setText("Inventory ID");

        jInventoryName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jInventoryName.setText("Inventory Name");

        jQuantity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jQuantity.setText("Quantity");

        jRate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRate.setText("Rate");

        jTotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTotal.setText("Total");

        jCash.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCash.setText("Cash");

        jCredit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jCredit.setText("Credit");

        jTextFieldMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMemberid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMemberidActionPerformed(evt);
            }
        });
        jTextFieldMemberid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMemberidKeyPressed(evt);
            }
        });

        jTextFieldMemberName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldInventoryId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldInventoryId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldInventoryIdKeyPressed(evt);
            }
        });

        jTextFieldInventoryName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldQuantity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQuantityKeyPressed(evt);
            }
        });

        jTextFieldRate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRateKeyPressed(evt);
            }
        });

        jTextFieldTotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldCash.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCashKeyPressed(evt);
            }
        });

        jTextFieldCredit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreditActionPerformed(evt);
            }
        });

        jButtonProceed.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonViewinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewinventory.setText("View Inventory");
        jButtonViewinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewinventoryActionPerformed(evt);
            }
        });

        jButtonCreateinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateinventory.setText("Create Inventory");
        jButtonCreateinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateinventoryActionPerformed(evt);
            }
        });

        jButtonAddinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddinventory.setText("Add Inventory");
        jButtonAddinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddinventoryActionPerformed(evt);
            }
        });

        jButtonViewmemberinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewmemberinventory.setText("View Member-Inventory");
        jButtonViewmemberinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewmemberinventoryActionPerformed(evt);
            }
        });

        jButtonViewsupplierinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewsupplierinventory.setText("View Supplier-Inventory");
        jButtonViewsupplierinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewsupplierinventoryActionPerformed(evt);
            }
        });

        jButtonBack1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack1.setText("Back");
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });

        jButtonHome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonIssuetomember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonIssuetomember.setText("Issue To Member");
        jButtonIssuetomember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIssuetomemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreateinventory)
                    .addComponent(jButtonAddinventory)
                    .addComponent(jButtonViewmemberinventory)
                    .addComponent(jButtonViewsupplierinventory)
                    .addComponent(jButtonBack1)
                    .addComponent(jButtonHome)
                    .addComponent(jButtonIssuetomember)
                    .addComponent(jButtonViewinventory)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonIssuetomember)
                .addGap(27, 27, 27)
                .addComponent(jButtonCreateinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonAddinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonViewmemberinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonViewsupplierinventory)
                .addGap(36, 36, 36)
                .addComponent(jButtonViewinventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonBack1)
                .addGap(29, 29, 29)
                .addComponent(jButtonHome)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jIssueHead)
                .addGap(334, 334, 334))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonProceed)
                                .addGap(50, 50, 50)
                                .addComponent(jButtonClear)
                                .addGap(55, 55, 55)
                                .addComponent(jButtonBack))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCredit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMemberid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMemberName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jIneventroryId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldInventoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jInventoryName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldInventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCash, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jIssue)
                        .addGap(248, 248, 248))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jIssueHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jIssue)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMemberid)
                            .addComponent(jTextFieldMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMemberName)
                            .addComponent(jTextFieldMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIneventroryId)
                            .addComponent(jTextFieldInventoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInventoryName)
                            .addComponent(jTextFieldInventoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQuantity)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRate)
                            .addComponent(jTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTotal)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCash)
                            .addComponent(jTextFieldCash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCredit)
                            .addComponent(jTextFieldCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProceed)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMemberidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMemberidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMemberidActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldCash.setText(null);
        jTextFieldCredit.setText(null);
        jTextFieldInventoryId.setText(null);
        jTextFieldInventoryName.setText(null);
        jTextFieldMemberName.setText(null);
        jTextFieldMemberid.setText(null);
        jTextFieldQuantity.setText(null);
        jTextFieldRate.setText(null);
        jTextFieldTotal.setText(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // Back To Inventory
        new Inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
        // TODO add your handling code here:
        Integer Member_id=Integer.parseInt(jTextFieldMemberid.getText());
        String  Member_name=jTextFieldMemberName.getText();
        String  Inventory_id=jTextFieldInventoryId.getText();
        String Inventory_name=jTextFieldInventoryName.getText();
        Integer Quantity=Integer.parseInt(jTextFieldQuantity.getText());
        double Rate=Double.parseDouble(jTextFieldRate.getText());
        double Total=Double.parseDouble(jTextFieldTotal.getText());
        double Cash=Double.parseDouble(jTextFieldCash.getText());
        double Credit=Double.parseDouble(jTextFieldCredit.getText());
        Connection con= ConnectionProvider.getCon();
        ResultSet rs;
           try{
           
           //step3: create sql query and execute it
          String sql="insert into issue_member_inventory(Member_id,Member_name,Inventory_id,Inventory_name,Quantity,Rate,Total,Cash,Credit)values(?,?,?,?,?,?,?,?,?)";
           PreparedStatement st=con.prepareStatement(sql);
           st.setInt(1, Member_id);
           st.setString(2, Member_name);
           st.setString(3, Inventory_id);
           st.setString(4,Inventory_name);
           st.setInt(5, Quantity);
           st.setDouble(6, Rate);
           st.setDouble(7,Total);
           st.setDouble(8,Cash);
           st.setDouble(9,Credit);
           st.execute();
           String sql2="select Quantity from inventory where Inventory_id="+Inventory_id;
           int Quantity1=0;
           PreparedStatement st2=con.prepareStatement(sql2);
           rs=st2.executeQuery();
           while(rs.next()){
               Quantity1=rs.getInt("Quantity");
           }
           Quantity1=Quantity1+Quantity;
           String sql3="update inventory set Quantity="+Quantity1 +" where Inventory_id="+Inventory_id;
           PreparedStatement st3=con.prepareStatement(sql3);
           st3.execute();
          //step4: close the connection
          
           con.close();
               JOptionPane.showMessageDialog(rootPane, "Sucessfully done");
           }
       catch(Exception ex){
            System.out.println(ex);
}
           try {
                    jTextFieldCash.setText(null);
        jTextFieldCredit.setText(null);
        jTextFieldInventoryId.setText(null);
        jTextFieldInventoryName.setText(null);
        jTextFieldMemberName.setText(null);
        jTextFieldMemberid.setText(null);
        jTextFieldQuantity.setText(null);
        jTextFieldRate.setText(null);
        jTextFieldTotal.setText(null);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonProceedActionPerformed

    private void jTextFieldRateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRateKeyPressed
        // TODO add your handling code here:
           // TODO add your handling code here:
        try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || 
                evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT|| 
                evt.getKeyCode()==KeyEvent.VK_DECIMAL) {
            jTextFieldRate.setEditable(true);
        }
        else{
            jTextFieldRate.setEditable(false);
        }
        } catch (Exception e) {
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int total_quantity=Integer.parseInt(jTextFieldQuantity.getText());
            double rate=Double.parseDouble(jTextFieldRate.getText());
            double total=0;
            total=total_quantity*rate;
            jTextFieldTotal.setText(String.valueOf(total));    
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN ) {
            jTextFieldCash.requestFocus();
            
        }
    }//GEN-LAST:event_jTextFieldRateKeyPressed

    private void jTextFieldCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCashKeyPressed
        // TODO add your handling code here:
        try {
              try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || 
                evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT|| 
                evt.getKeyCode()==KeyEvent.VK_DECIMAL) {
            jTextFieldCash.setEditable(true);
        }
        else{
            jTextFieldCash.setEditable(false);
        }
        } catch (Exception e) {
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        double cash=Double.parseDouble(jTextFieldCash.getText());
        double total=Double.parseDouble(jTextFieldTotal.getText());
        double credit=0;
        credit=total-cash;
        jTextFieldCredit.setText(String.valueOf(credit));
        jTextFieldCredit.setEditable(false);
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldCashKeyPressed

    private void jTextFieldMemberidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMemberidKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
        Integer Member_id=Integer.parseInt(jTextFieldMemberid.getText());
        Connection con= ConnectionProvider.getCon();
        ResultSet rs = null;
           try{
           
           //step3: create sql query and execute it
           String sql="select Full_name from member where Member_id="+Member_id;
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
               if (rs==null) {
                   System.out.println("Hello");
               }
           while(rs.next()){
               String Member_name=rs.getString("Full_name");
               jTextFieldMemberName.setText(Member_name);
           }
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
  JOptionPane.showMessageDialog(rootPane, "Invalid account no");
       }
           jTextFieldInventoryId.requestFocus();
      }
    }//GEN-LAST:event_jTextFieldMemberidKeyPressed

    private void jTextFieldInventoryIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInventoryIdKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
        Integer Inventory_id=Integer.parseInt(jTextFieldInventoryId.getText());
       Connection con= ConnectionProvider.getCon();
        ResultSet rs = null;
           try{
          
           //step3: create sql query and execute it
           String sql="select Inventory_name from Inventory where Inventory_id="+Inventory_id;
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
           while(rs.next()){
               String Inventory_name=rs.getString("Inventory_name");
               jTextFieldInventoryName.setText(Inventory_name);
           }
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
  JOptionPane.showMessageDialog(rootPane, "Invalid Inventory id");
       }
           jTextFieldQuantity.requestFocus();
      }
    }//GEN-LAST:event_jTextFieldInventoryIdKeyPressed

    private void jTextFieldQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantityKeyPressed
        // TODO add your handling code here:
         try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||
                evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || 
                evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT|| 
                evt.getKeyCode()==KeyEvent.VK_DECIMAL) {
                jTextFieldQuantity.setEditable(true);
        }
        else{
            jTextFieldQuantity.setEditable(false);
        }
        } catch (Exception e) {
        }
               if (evt.getKeyCode() == KeyEvent.VK_ENTER ) {
             jTextFieldRate.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldQuantityKeyPressed

    private void jButtonViewinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewinventoryActionPerformed
        // TODO add your handling code here:
       new ViewInventory().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButtonViewinventoryActionPerformed

    private void jButtonCreateinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateinventoryActionPerformed
        // TODO add your handling code here:
        new Createinventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateinventoryActionPerformed

    private void jButtonAddinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddinventoryActionPerformed
        // TODO add your handling code here:
        new AddNewInventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonAddinventoryActionPerformed

    private void jButtonViewsupplierinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewsupplierinventoryActionPerformed
        // TODO add your handling code here:
        new Supplier_inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewsupplierinventoryActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        // TODO add your handling code here:
        new Inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonIssuetomemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIssuetomemberActionPerformed
        // TODO add your handling code here:
        new Issuetomember().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonIssuetomemberActionPerformed

    private void jButtonViewmemberinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewmemberinventoryActionPerformed
        // TODO add your handling code here:
        new Member_inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewmemberinventoryActionPerformed

    private void jTextFieldCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issuetomember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issuetomember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issuetomember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issuetomember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issuetomember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddinventory;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCreateinventory;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonIssuetomember;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonViewinventory;
    private javax.swing.JButton jButtonViewmemberinventory;
    private javax.swing.JButton jButtonViewsupplierinventory;
    private javax.swing.JLabel jCash;
    private javax.swing.JLabel jCredit;
    private javax.swing.JLabel jIneventroryId;
    private javax.swing.JLabel jInventoryName;
    private javax.swing.JLabel jIssue;
    private javax.swing.JLabel jIssueHead;
    private javax.swing.JLabel jMemberName;
    private javax.swing.JLabel jMemberid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jQuantity;
    private javax.swing.JLabel jRate;
    private javax.swing.JTextField jTextFieldCash;
    private javax.swing.JTextField jTextFieldCredit;
    private javax.swing.JTextField jTextFieldInventoryId;
    private javax.swing.JTextField jTextFieldInventoryName;
    private javax.swing.JTextField jTextFieldMemberName;
    private javax.swing.JTextField jTextFieldMemberid;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldRate;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JLabel jTotal;
    // End of variables declaration//GEN-END:variables
}
