/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Loan;

import Account.ViewAccounts;
import Account.Viewtransactions;
import ConnectionProvider.ConnectionProvider;
import Home.Home;
import Member.ViewMember;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell
 */
public class IssueLoan extends javax.swing.JFrame {

    /**
     * Creates new form IssueLoan
     */
    
    Date Datefortable=new Date(System.currentTimeMillis());
    Date IssuedDate=new Date(System.currentTimeMillis());
    
    public IssueLoan() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jIssueHead = new javax.swing.JLabel();
        jIssueLoan = new javax.swing.JLabel();
        jMemberid = new javax.swing.JLabel();
        jMemberName = new javax.swing.JLabel();
        jLoanAmount = new javax.swing.JLabel();
        jLoanPeriod = new javax.swing.JLabel();
        jTypesofLoan = new javax.swing.JLabel();
        jTextFieldMemberid = new javax.swing.JTextField();
        jTextFieldMembername = new javax.swing.JTextField();
        jTextFieldLoanAmount = new javax.swing.JTextField();
        jTextFieldLoanPeriod = new javax.swing.JTextField();
        jComboBoxTypesofloan = new javax.swing.JComboBox<>();
        jProceed = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jPanelSideBar = new javax.swing.JPanel();
        jButtonViewAccount = new javax.swing.JButton();
        jButtonCreateaccount = new javax.swing.JButton();
        jButtonViewmember = new javax.swing.JButton();
        jButtonViewLoans = new javax.swing.JButton();
        jButtonTransactions = new javax.swing.JButton();
        jButtonRepayment = new javax.swing.JButton();
        jButtonhome = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jRateofLoan = new javax.swing.JLabel();
        jTextFieldRateofloan = new javax.swing.JTextField();
        jTextFieldTotalnoofpayments = new javax.swing.JTextField();
        jRateofLoan1 = new javax.swing.JLabel();
        jRateofLoan2 = new javax.swing.JLabel();
        jTextFieldNoofpaymentsinyear = new javax.swing.JTextField();
        jLabelLoanid = new javax.swing.JLabel();
        jTextFieldLoanid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jIssueHead.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jIssueHead.setText("Pashupati Mahila JibikoParjan Krishi Sahakari Sanstha ");

        jIssueLoan.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jIssueLoan.setText("Issue Loan");

        jMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMemberid.setText("Member id:");

        jMemberName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMemberName.setText("Member Name:");

        jLoanAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLoanAmount.setText("Loan Amount:");

        jLoanPeriod.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLoanPeriod.setText("Loan Period:");

        jTypesofLoan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTypesofLoan.setText("Types of Loan:");

        jTextFieldMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMemberid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMemberidActionPerformed(evt);
            }
        });
        jTextFieldMemberid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMemberidKeyPressed(evt);
            }
        });

        jTextFieldMembername.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMembername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMembernameActionPerformed(evt);
            }
        });

        jTextFieldLoanAmount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldLoanAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoanAmountActionPerformed(evt);
            }
        });
        jTextFieldLoanAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLoanAmountKeyPressed(evt);
            }
        });

        jTextFieldLoanPeriod.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldLoanPeriod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLoanPeriodKeyPressed(evt);
            }
        });

        jComboBoxTypesofloan.setFont(new java.awt.Font("Calibri", 0, 18));
        jComboBoxTypesofloan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Farming Loan", "Animal Husbandary Loan", "Agriculture Equipment Loan", "Other Loan" }));
        jComboBoxTypesofloan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTypesofloanItemStateChanged(evt);
            }
        });
        jComboBoxTypesofloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypesofloanActionPerformed(evt);
            }
        });

        jProceed.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jProceed.setText("Proceed");
        jProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProceedActionPerformed(evt);
            }
        });

        jClear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jClear.setText("Amortization");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jAdd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jButtonViewAccount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewAccount.setText("View Accounts");
        jButtonViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAccountActionPerformed(evt);
            }
        });

        jButtonCreateaccount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateaccount.setText("Issue Loan");
        jButtonCreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateaccountActionPerformed(evt);
            }
        });

        jButtonViewmember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewmember.setText("View Members");
        jButtonViewmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewmemberActionPerformed(evt);
            }
        });

        jButtonViewLoans.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewLoans.setText("View Loans");
        jButtonViewLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewLoansActionPerformed(evt);
            }
        });

        jButtonTransactions.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonTransactions.setText("Transactions");
        jButtonTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransactionsActionPerformed(evt);
            }
        });

        jButtonRepayment.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonRepayment.setText("Repayment of Loan");
        jButtonRepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepaymentActionPerformed(evt);
            }
        });

        jButtonhome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonhome.setText("Home");
        jButtonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhomeActionPerformed(evt);
            }
        });

        jButtonback.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSideBarLayout = new javax.swing.GroupLayout(jPanelSideBar);
        jPanelSideBar.setLayout(jPanelSideBarLayout);
        jPanelSideBarLayout.setHorizontalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addGroup(jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewLoans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreateaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRepayment, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jButtonhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSideBarLayout.setVerticalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonCreateaccount)
                .addGap(26, 26, 26)
                .addComponent(jButtonRepayment)
                .addGap(18, 18, 18)
                .addComponent(jButtonViewLoans)
                .addGap(31, 31, 31)
                .addComponent(jButtonViewmember)
                .addGap(36, 36, 36)
                .addComponent(jButtonViewAccount)
                .addGap(27, 27, 27)
                .addComponent(jButtonTransactions)
                .addGap(33, 33, 33)
                .addComponent(jButtonback)
                .addGap(27, 27, 27)
                .addComponent(jButtonhome)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jRateofLoan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRateofLoan.setText("Rate Of Loan");

        jTextFieldRateofloan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldRateofloan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRateofloanFocusGained(evt);
            }
        });
        jTextFieldRateofloan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRateofloanActionPerformed(evt);
            }
        });
        jTextFieldRateofloan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRateofloanKeyPressed(evt);
            }
        });

        jTextFieldTotalnoofpayments.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldTotalnoofpayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalnoofpaymentsActionPerformed(evt);
            }
        });
        jTextFieldTotalnoofpayments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTotalnoofpaymentsKeyPressed(evt);
            }
        });

        jRateofLoan1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRateofLoan1.setText("No. Of payments Per Year");

        jRateofLoan2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRateofLoan2.setText("Total No.of Payments");

        jTextFieldNoofpaymentsinyear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNoofpaymentsinyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNoofpaymentsinyearActionPerformed(evt);
            }
        });
        jTextFieldNoofpaymentsinyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNoofpaymentsinyearKeyPressed(evt);
            }
        });

        jLabelLoanid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelLoanid.setText("Loan Id");

        jTextFieldLoanid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Due Date", "Year", "PMT", "Interest", "Principal", "Loan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.setRowMargin(5);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jIssueLoan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jIssueHead))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanelSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRateofLoan1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jProceed)))
                                        .addGap(41, 41, 41)
                                        .addComponent(jClear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(jAdd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelLoanid)
                                            .addComponent(jRateofLoan2)
                                            .addComponent(jRateofLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTypesofLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLoanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLoanid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldMemberid)
                                            .addComponent(jTextFieldMembername)
                                            .addComponent(jTextFieldLoanAmount)
                                            .addComponent(jTextFieldLoanPeriod)
                                            .addComponent(jComboBoxTypesofloan, 0, 200, Short.MAX_VALUE))
                                        .addComponent(jTextFieldRateofloan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNoofpaymentsinyear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldTotalnoofpayments, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(776, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jIssueHead)
                .addGap(25, 25, 25)
                .addComponent(jIssueLoan)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldMembername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLoanAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLoanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLoanPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxTypesofloan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTypesofLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldRateofloan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRateofLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jRateofLoan1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jTextFieldNoofpaymentsinyear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRateofLoan2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTotalnoofpayments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLoanid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLoanid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAdd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jClear)
                        .addComponent(jProceed)))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMemberidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMemberidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMemberidActionPerformed

    private void jTextFieldMembernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMembernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMembernameActionPerformed

    private void jTextFieldLoanAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoanAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoanAmountActionPerformed

    private void jComboBoxTypesofloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypesofloanActionPerformed
        // TODO add your handling code here:
         String Typesofloan=String.valueOf(jComboBoxTypesofloan.getSelectedItem());
        if (Typesofloan.equalsIgnoreCase("Farming Loan")||Typesofloan.equalsIgnoreCase("Animal Husbandary Loan")||Typesofloan.equalsIgnoreCase("Agriculture Equipment Loan")) {
            jTextFieldRateofloan.setText("13");
        }
        else if (Typesofloan.equalsIgnoreCase("Other Loan")) {
            jTextFieldRateofloan.setText("15");
        }
        jTextFieldRateofloan.setEditable(false);
    }//GEN-LAST:event_jComboBoxTypesofloanActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        // Back
              ResultSet rs;
                           Connection con= ConnectionProvider.getCon();

         con=null;
        int Member_id=Integer.parseInt(jTextFieldMemberid.getText());
        int Loan_id=Integer.parseInt(jTextFieldLoanid.getText());
        int Period=Integer.parseInt(jTextFieldLoanPeriod.getText());
        double Loan_amount=Double.parseDouble(jTextFieldLoanAmount.getText());
        double Rate_of_loan=(Double.parseDouble(jTextFieldRateofloan.getText()))/100;
        int No_of_payments=Integer.parseInt(jTextFieldTotalnoofpayments.getText());
        int Year=Integer.parseInt(jTextFieldLoanPeriod.getText());
        double pmt=0;
        double interest=0;
        double principal=0;
        

        pmt=Loan_amount*Rate_of_loan/(1-((1/(Math.pow((1+Rate_of_loan),No_of_payments)))));

        try {
           
           String  pmt2=String.format("%.4f",pmt);
           String sql1="Insert into remaining_loan(Loan_id,Member_id,Remaining_loanAmount,Loan_pmt) values(?,?,?,?)";
           PreparedStatement st1=con.prepareStatement(sql1);
           st1.setInt(1, Loan_id);
           st1.setInt(2, Member_id);
           st1.setDouble(3, Loan_amount);
           st1.setString(4, pmt2);
           st1.execute();
            for (int i = 0; i <= No_of_payments; i++) {
            
            if (i==0) {
                String Loan3=String.format("%.4f",Loan_amount);
           String sql="insert into loan_amortization(Due_date,Loan_id,Member_id,Year,pmt,Interest,Principal,Loan) values(?,?,?,?,?,?,?,?)";
           PreparedStatement st=con.prepareStatement(sql);
           st.setDate(1, IssuedDate);
           st.setInt(2, Loan_id);
           st.setInt(3, Member_id);
           st.setInt(4,i);
           st.setDouble(5,0);
           st.setDouble(6, 0);
           st.setDouble(7,0 );
           st.setString(8, Loan3);
           st.execute();
                
            }
            else{
                
                IssuedDate.setMonth(19);
                pmt=pmt;
                interest=Loan_amount*Rate_of_loan;
                principal=pmt-interest;
                Loan_amount=Loan_amount-principal;
            String  pmt1=String.format("%.4f",pmt);
            String Interest1=String.format("%.4f",interest);
            String principal1=String.format("%.4f",principal);
             String Loan2=String.format("%.4f",Loan_amount);
           String sql="insert into loan_amortization(Due_date,Loan_id,Member_id,"
                   + "Year,pmt,Interest,Principal,Loan) values(?,?,?,?,?,?,?,?)";
           PreparedStatement st=con.prepareStatement(sql);
           st.setDate(1, IssuedDate);
           st.setInt(2, Loan_id);
           st.setInt(3, Member_id);
           st.setInt(4,i);
           st.setString(5,pmt1);
           st.setString(6, Interest1);
           st.setString(7,principal1);
           st.setString(8, Loan2);
           st.execute();
           //SQL To add on remaining loan table
           
            }
            
            
        }
   
         con.close();
               JOptionPane.showMessageDialog(rootPane,"Successfully Added To "
                       + "Amortization Table");
        } catch (Exception e) {
            System.out.println(e);
        }
        try {
            jTextFieldLoanid.setText(null);
            jTextFieldMemberid.setText(null);
            jTextFieldMembername.setText(null);
            jTextFieldNoofpaymentsinyear.setText(null);
            jTextFieldRateofloan.setText(null);
            jTextFieldLoanAmount.setText(null);
            jTextFieldLoanPeriod.setText(null);
            jTextFieldTotalnoofpayments.setText(null);
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jAddActionPerformed

    private void jProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProceedActionPerformed
        // TODO add your handling code here:
        Integer Member_id=Integer.parseInt(jTextFieldMemberid.getText());
        String Member_name=jTextFieldMembername.getText();
        Integer Amount=Integer.parseInt(jTextFieldLoanAmount.getText());
        Integer Loan_period=Integer.parseInt(jTextFieldLoanPeriod.getText());
        String Loan_type=String.valueOf(jComboBoxTypesofloan.getSelectedItem());
        double Rate_ofloan=Double.parseDouble(jTextFieldRateofloan.getText());
        Integer No_of_payementsperyear=Integer.parseInt(jTextFieldNoofpaymentsinyear.getText());
        Integer Total_no_of_payments=Integer.parseInt(jTextFieldTotalnoofpayments.getText());
        ResultSet rs;
           try{
            Connection con= ConnectionProvider.getCon();
           //step3: create sql query and execute it
          String sql="insert into loan(Member_id,Member_name,Loan_amount,Loan_period,Types_of_loan,Rate_ofloan,No_of_paymentsperyear,Total_no_of_payments)values(?,?,?,?,?,?,?,?)";
           PreparedStatement st=con.prepareStatement(sql);
           st.setInt(1, Member_id);
           st.setString(2, Member_name);
           st.setInt(3, Amount);
           st.setInt(4,Loan_period);
           st.setString(5,Loan_type);
           st.setDouble(6, Rate_ofloan);
           st.setInt(7, No_of_payementsperyear);
           st.setInt(8, Total_no_of_payments);
           st.execute();
          //step4: close the connection
           con.close();
               JOptionPane.showMessageDialog(rootPane, "Sucessfully Issued "
                       + "of Amount"+Amount);
           }
       catch(Exception ex){
            System.out.println(ex);
}   
         
    }//GEN-LAST:event_jProceedActionPerformed

    private void jTextFieldMemberidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMemberidKeyPressed
        // TODO add your handling code here:
        try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldMemberid.setEditable(true);
        }
        else{
            jTextFieldMemberid.setEditable(false);
        }
        } catch (Exception e) {
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || 
                evt.getKeyCode() == KeyEvent.VK_DOWN || 
                evt.getKeyCode() == KeyEvent.VK_RIGHT) {
        Integer Member_id=Integer.parseInt(jTextFieldMemberid.getText());
        
        ResultSet rs = null;
           try{
             Connection con= ConnectionProvider.getCon();
           //step3: create sql query and execute it
           String sql="select Full_name from member where Member_id="+Member_id;
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
               if (rs==null) {
                   System.out.println("Hello");
               }
           while(rs.next()){
               String Member_name=rs.getString("Full_name");
               jTextFieldMembername.setText(Member_name);
           }
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
  JOptionPane.showMessageDialog(rootPane, "Invalid account no");
       }
           jTextFieldLoanAmount.requestFocus();
      }
    }//GEN-LAST:event_jTextFieldMemberidKeyPressed

    private void jTextFieldLoanAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoanAmountKeyPressed
        // TODO add your handling code here:
        try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_DECIMAL||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldLoanAmount.setEditable(true);
        }
        else{
            jTextFieldLoanAmount.setEditable(false);
        }
        } catch (Exception e) {
        }
         try {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldLoanPeriod.requestFocus();
        } 
        } catch (Exception e){
            
        }
       
    }//GEN-LAST:event_jTextFieldLoanAmountKeyPressed

    private void jTextFieldLoanPeriodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoanPeriodKeyPressed
        // TODO add your handling code here:
                try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_DECIMAL||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldLoanPeriod.setEditable(true);
        }
        else{
            jTextFieldLoanPeriod.setEditable(false);
        }
        } catch (Exception e) {
        }
                 try {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jComboBoxTypesofloan.requestFocus();
        } 
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_jTextFieldLoanPeriodKeyPressed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed

    
    int Member_id=Integer.parseInt(jTextFieldMemberid.getText());
    int Loan_id=0;
    int Period=Integer.parseInt(jTextFieldLoanPeriod.getText());
    double Loan_amount=Double.parseDouble(jTextFieldLoanAmount.getText());
    double Rate_of_loan=(Double.parseDouble(jTextFieldRateofloan.getText()))/100;
    int No_of_payments=Integer.parseInt(jTextFieldTotalnoofpayments.getText());
    int Year=Integer.parseInt(jTextFieldLoanPeriod.getText());
    int loan_amount=Integer.parseInt(jTextFieldLoanAmount.getText());
    String Loan_type=String.valueOf(jComboBoxTypesofloan.getSelectedItem());
    double Rate_ofloan=Double.parseDouble(jTextFieldRateofloan.getText());
    double pmt=0;
    double interest=0;
    double principal=0;
    //For Displaying Loan ID
            Connection con= ConnectionProvider.getCon();
        ResultSet rs;
        try {
           
            String sql="Select * from Loan where Member_id=? and Loan_amount=? "
                    + "and Loan_period=? and Rate_ofloan=? and Types_of_loan=?";        
               PreparedStatement st=con.prepareStatement(sql);
               st.setInt(1, Member_id);
               st.setInt(2, loan_amount);
               st.setInt(3, Period);
               st.setDouble(4, Rate_ofloan);
               st.setString(5, Loan_type);
               rs=st.executeQuery();
               while(rs.next()){
                   jTextFieldLoanid.setText(String.valueOf(rs.getInt("Loan_id")));
                   IssuedDate=rs.getDate("Issued_date_time");
                   Datefortable=rs.getDate("Issued_date_time");
               }
        } catch (Exception e) {
            System.out.println(e);
        }
    //For Amortization Table
    pmt=Loan_amount*Rate_of_loan/(1-((1/(Math.pow((1+Rate_of_loan),No_of_payments)))));
      
    for (int i = 0; i <= No_of_payments; i++) {
                      String Loan1=String.valueOf(Loan_amount);
                       String i1=String.valueOf(i);
                       String issueddateString=String.valueOf(IssuedDate);
                       

            if (i==0) {
                String table_data[]={issueddateString,i1,"","","",Loan1};
                DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
                tablemodel.addRow(table_data); 
            }
            else{
            Datefortable.setMonth(19);
            String issueddatestring=String.valueOf(Datefortable);
            pmt=pmt;
            interest=Loan_amount*Rate_of_loan;
            principal=pmt-interest;                
            String  pmt1=String.format("%.4f",pmt);
            String Interest1=String.format("%.4f",interest);
            String principal1=String.format("%.4f",principal);
             Loan_amount=Loan_amount-principal;
             String Loan2=String.format("%.4f",Loan_amount);
              String table_data[]={issueddatestring,i1,pmt1,Interest1,principal1,Loan2};
                DefaultTableModel tablemodel=(DefaultTableModel)jTable1.getModel();
                tablemodel.addRow(table_data);
                 
               
        }
        }
       
    }//GEN-LAST:event_jClearActionPerformed

    private void jButtonViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAccountActionPerformed
        // TODO add your handling code here:
        new ViewAccounts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewAccountActionPerformed

    private void jButtonCreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateaccountActionPerformed
        // TODO add your handling code here:
        new IssueLoan().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateaccountActionPerformed

    private void jButtonViewmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewmemberActionPerformed
        // TODO add your handling code here:
        new ViewMember().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButtonViewmemberActionPerformed

    private void jButtonViewLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewLoansActionPerformed
        // TODO add your handling code here:
        new Viewloans().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewLoansActionPerformed

    private void jButtonTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransactionsActionPerformed
        // TODO add your handling code here:
        new Viewtransactions().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonTransactionsActionPerformed

    private void jButtonRepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepaymentActionPerformed
        // TODO add your handling code here:
         new RepaymentOfLoan().setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButtonRepaymentActionPerformed

    private void jButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonhomeActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jTextFieldRateofloanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRateofloanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRateofloanActionPerformed

    private void jTextFieldRateofloanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRateofloanKeyPressed
        // TODO add your handling code here:
      try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_DECIMAL||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldRateofloan.setEditable(true);
        }
        else{
            jTextFieldRateofloan.setEditable(false);
        }
        } catch (Exception e) {
        }
                 try {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT) {
            jTextFieldNoofpaymentsinyear.requestFocus();
        } 
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_jTextFieldRateofloanKeyPressed

    private void jTextFieldTotalnoofpaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalnoofpaymentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalnoofpaymentsActionPerformed

    private void jTextFieldTotalnoofpaymentsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalnoofpaymentsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalnoofpaymentsKeyPressed

    private void jTextFieldNoofpaymentsinyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNoofpaymentsinyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNoofpaymentsinyearActionPerformed

    private void jTextFieldNoofpaymentsinyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNoofpaymentsinyearKeyPressed
        // TODO add your handling code here:
            try {
             char c=evt.getKeyChar();
        if (Character.isDigit(c)|| evt.getKeyCode()==KeyEvent.VK_DECIMAL||evt.getKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getKeyCode()==KeyEvent.VK_DELETE||evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jTextFieldNoofpaymentsinyear.setEditable(true);
        }
        else{
            jTextFieldNoofpaymentsinyear.setEditable(false);
        }
        } catch (Exception e) {
        }
                 try {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER||evt.getKeyCode()==KeyEvent.VK_DOWN||evt.getKeyCode()==KeyEvent.VK_LEFT||evt.getKeyCode()==KeyEvent.VK_RIGHT) {
             Integer Loan_period=Integer.parseInt(jTextFieldLoanPeriod.getText());
        Integer No_of_payementsperyear=Integer.parseInt(jTextFieldNoofpaymentsinyear.getText());
        Integer Total_no_of_payments=Loan_period*No_of_payementsperyear;
        jTextFieldTotalnoofpayments.setText(String.valueOf(Total_no_of_payments));
                jTextFieldTotalnoofpayments.requestFocus();
                jTextFieldTotalnoofpayments.setEditable(false);
        } 
        } catch (Exception e){
            
        }
                 
        
    }//GEN-LAST:event_jTextFieldNoofpaymentsinyearKeyPressed

    private void jComboBoxTypesofloanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTypesofloanItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBoxTypesofloanItemStateChanged

    private void jTextFieldRateofloanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRateofloanFocusGained
        // TODO add your handling code here:
        String Typesofloan=String.valueOf(jComboBoxTypesofloan.getSelectedItem());
        if (Typesofloan.equalsIgnoreCase("Farming Loan")||Typesofloan.equalsIgnoreCase("Animal Husbandary Loan")||Typesofloan.equalsIgnoreCase("Agriculture Equipment Loan")) {
            jTextFieldRateofloan.setText("13");
        }
        else if (Typesofloan.equalsIgnoreCase("Other Loan")) {
            jTextFieldRateofloan.setText("15");
        }
        jTextFieldRateofloan.setEditable(false);
    }//GEN-LAST:event_jTextFieldRateofloanFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueLoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         System.err.println();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueLoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jButtonCreateaccount;
    private javax.swing.JButton jButtonRepayment;
    private javax.swing.JButton jButtonTransactions;
    private javax.swing.JButton jButtonViewAccount;
    private javax.swing.JButton jButtonViewLoans;
    private javax.swing.JButton jButtonViewmember;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonhome;
    private javax.swing.JButton jClear;
    private javax.swing.JComboBox<String> jComboBoxTypesofloan;
    private javax.swing.JLabel jIssueHead;
    private javax.swing.JLabel jIssueLoan;
    private javax.swing.JLabel jLabelLoanid;
    private javax.swing.JLabel jLoanAmount;
    private javax.swing.JLabel jLoanPeriod;
    private javax.swing.JLabel jMemberName;
    private javax.swing.JLabel jMemberid;
    private javax.swing.JPanel jPanelSideBar;
    private javax.swing.JButton jProceed;
    private javax.swing.JLabel jRateofLoan;
    private javax.swing.JLabel jRateofLoan1;
    private javax.swing.JLabel jRateofLoan2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLoanAmount;
    private javax.swing.JTextField jTextFieldLoanPeriod;
    private javax.swing.JTextField jTextFieldLoanid;
    private javax.swing.JTextField jTextFieldMemberid;
    private javax.swing.JTextField jTextFieldMembername;
    private javax.swing.JTextField jTextFieldNoofpaymentsinyear;
    private javax.swing.JTextField jTextFieldRateofloan;
    private javax.swing.JTextField jTextFieldTotalnoofpayments;
    private javax.swing.JLabel jTypesofLoan;
    // End of variables declaration//GEN-END:variables
}
