/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Loan;

import Account.ViewAccounts;
import Account.Viewtransactions;
import ConnectionProvider.ConnectionProvider;
import Home.Home;
import Member.ViewMember;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Viewloans extends javax.swing.JFrame {

    /**
     * Creates new form Viewloans
     */
    public Viewloans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSideBar = new javax.swing.JPanel();
        jButtonViewAccount = new javax.swing.JButton();
        jButtonCreateaccount = new javax.swing.JButton();
        jButtonViewmember = new javax.swing.JButton();
        jButtonViewLoans = new javax.swing.JButton();
        jButtonTransactions = new javax.swing.JButton();
        jButtonRepayment = new javax.swing.JButton();
        jButtonhome = new javax.swing.JButton();
        jButtonback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLoans = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotalLoanIssued = new javax.swing.JTextField();
        jButtonViewTotal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        jButtonSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooserFrom = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonViewAccount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewAccount.setText("View Accounts");
        jButtonViewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAccountActionPerformed(evt);
            }
        });

        jButtonCreateaccount.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateaccount.setText("Issue Loan");
        jButtonCreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateaccountActionPerformed(evt);
            }
        });

        jButtonViewmember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewmember.setText("View Members");
        jButtonViewmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewmemberActionPerformed(evt);
            }
        });

        jButtonViewLoans.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewLoans.setText("View Loans");
        jButtonViewLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewLoansActionPerformed(evt);
            }
        });

        jButtonTransactions.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonTransactions.setText("Transactions");
        jButtonTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransactionsActionPerformed(evt);
            }
        });

        jButtonRepayment.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonRepayment.setText("Repayment of Loan");
        jButtonRepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepaymentActionPerformed(evt);
            }
        });

        jButtonhome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonhome.setText("Home");
        jButtonhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhomeActionPerformed(evt);
            }
        });

        jButtonback.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonback.setText("Back");
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSideBarLayout = new javax.swing.GroupLayout(jPanelSideBar);
        jPanelSideBar.setLayout(jPanelSideBarLayout);
        jPanelSideBarLayout.setHorizontalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addGroup(jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRepayment, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jButtonhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonViewLoans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreateaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSideBarLayout.setVerticalGroup(
            jPanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButtonViewLoans)
                .addGap(32, 32, 32)
                .addComponent(jButtonCreateaccount)
                .addGap(26, 26, 26)
                .addComponent(jButtonRepayment)
                .addGap(18, 18, 18)
                .addComponent(jButtonViewmember)
                .addGap(27, 27, 27)
                .addComponent(jButtonViewAccount)
                .addGap(27, 27, 27)
                .addComponent(jButtonTransactions)
                .addGap(33, 33, 33)
                .addComponent(jButtonback)
                .addGap(27, 27, 27)
                .addComponent(jButtonhome)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTableLoans.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTableLoans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan ID", "Member ID", "Member Name", "Loan Amount", "Loan Period", "Issued Date", "Types of Loan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLoans.setRowHeight(30);
        jTableLoans.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLoans);
        if (jTableLoans.getColumnModel().getColumnCount() > 0) {
            jTableLoans.getColumnModel().getColumn(0).setResizable(false);
            jTableLoans.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Total Loan Issued:");

        jTextFieldTotalLoanIssued.setEditable(false);
        jTextFieldTotalLoanIssued.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jButtonViewTotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewTotal.setText("View");
        jButtonViewTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewTotalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("From");

        jButtonSearch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Search By Date");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("To");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanelSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113)
                        .addComponent(jTextFieldTotalLoanIssued, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(726, 726, 726)
                .addComponent(jButtonViewTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jDateChooserTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(364, 364, 364))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSearch)
                        .addGap(414, 414, 414))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(434, 434, 434))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTotalLoanIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonViewTotal)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAccountActionPerformed
        // TODO add your handling code here:
        new ViewAccounts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewAccountActionPerformed

    private void jButtonCreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateaccountActionPerformed
        // TODO add your handling code here:
        new IssueLoan().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateaccountActionPerformed

    private void jButtonViewmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewmemberActionPerformed
        // TODO add your handling code here:
        new ViewMember().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewmemberActionPerformed

    private void jButtonViewLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewLoansActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
               jTableLoans.setModel(new DefaultTableModel(null,new String [] {
            "Loan ID", "Member ID", "Member Name","Loan Amount","Loan Period","Issued Date","Types of Loan"
        }));
                            Connection con= ConnectionProvider.getCon();

                ResultSet rs;
               
                try{
                    
                    //step3: create sql query and execute it
                    String sql="select * from Loan ";
                    PreparedStatement st=con.prepareStatement(sql);
                    rs=st.executeQuery();
                    
                    while (rs.next()) {
                        String Loan_ID=String.valueOf(rs.getInt("Loan_id"));
                        String Member_ID=String.valueOf(rs.getInt("Member_id"));
                        String Member_name=rs.getString("Member_name");
                        String Loan_amount=String.valueOf(rs.getInt("Loan_amount"));
                        String Issued_date=String.valueOf(rs.getDate("Loan_issued_date"));
                        String Loan_period=String.valueOf(rs.getInt("Loan_period"));
                        String Types_ofloan=rs.getString("Types_of_loan");
                        String table_data[]={Loan_ID,Member_ID,Member_name,Loan_amount,Issued_date,Loan_period,Types_ofloan};
                        DefaultTableModel tablemodel=(DefaultTableModel)jTableLoans.getModel();
                        tablemodel.addRow(table_data);
                        
                    }
                    }
                catch(Exception ex){
                    
                }
    }//GEN-LAST:event_jButtonViewLoansActionPerformed

    private void jButtonTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransactionsActionPerformed
        // TODO add your handling code here:
        new Viewtransactions().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonTransactionsActionPerformed

    private void jButtonRepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepaymentActionPerformed
        // TODO add your handling code here:
        new RepaymentOfLoan().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonRepaymentActionPerformed

    private void jButtonhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonhomeActionPerformed

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void jButtonViewTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewTotalActionPerformed
        // TODO add your handling code here:
                     Connection con= ConnectionProvider.getCon();

        ResultSet rs;
           try{

//           step3: create sql query and execute it
           String sql="SELECT SUM(Loan_amount)  as TotalLoan FROM Loan;";
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
               if (rs.next()) {
                String Loan=rs.getString("TotalLoan");
                jTextFieldTotalLoanIssued.setText(Loan);
               }
 
               
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
            System.out.println(ex);
}
    }//GEN-LAST:event_jButtonViewTotalActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        jTableLoans.setModel(new DefaultTableModel(null,new String [] {
            "Loan ID", "Member ID", "Member Name","Loan Amount","Loan Period","Issued Date","Types of Loan"
        }));
                             Connection con= ConnectionProvider.getCon();

                ResultSet rs;
               SimpleDateFormat SDF=new SimpleDateFormat("yyyy-MM-dd");
              String DateFrom=SDF.format(jDateChooserFrom.getDate());
              String DateTo=SDF.format(jDateChooserTo.getDate());
                try{
                    //step3: create sql query and execute it
                    String sql="select * from Loan where Loan_issued_date between ? and ?  ";
                    PreparedStatement st=con.prepareStatement(sql);
                    st.setString(1, DateFrom);
                    st.setString(2, DateTo);
                    rs=st.executeQuery();
                    
                    while (rs.next()) {
                        String Loan_ID=String.valueOf(rs.getInt("Loan_id"));
                        String Member_ID=String.valueOf(rs.getInt("Member_id"));
                        String Member_name=rs.getString("Member_name");
                        String Loan_amount=String.valueOf(rs.getInt("Loan_amount"));
                        String Issued_date=String.valueOf(rs.getDate("Loan_issued_date"));
                        String Loan_period=String.valueOf(rs.getInt("Loan_period"));
                        String Types_ofloan=rs.getString("Types_of_loan");
                        String table_data[]={Loan_ID,Member_ID,Member_name,Loan_amount,Issued_date,Loan_period,Types_ofloan};
                        DefaultTableModel tablemodel=(DefaultTableModel)jTableLoans.getModel();
                        tablemodel.addRow(table_data);
                        
                    }
                    }
                catch(Exception ex){
                    
                }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewloans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewloans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewloans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewloans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewloans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateaccount;
    private javax.swing.JButton jButtonRepayment;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonTransactions;
    private javax.swing.JButton jButtonViewAccount;
    private javax.swing.JButton jButtonViewLoans;
    private javax.swing.JButton jButtonViewTotal;
    private javax.swing.JButton jButtonViewmember;
    private javax.swing.JButton jButtonback;
    private javax.swing.JButton jButtonhome;
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelSideBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLoans;
    private javax.swing.JTextField jTextFieldTotalLoanIssued;
    // End of variables declaration//GEN-END:variables
}
