/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SupplierDetails;
import ConnectionProvider.ConnectionProvider;
import Home.Home;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class AddNewSupplier extends javax.swing.JFrame {

    /**
     * Creates new form AddNewSupplier
     */
    public AddNewSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSupplierName = new javax.swing.JLabel();
        jSupplierAddress = new javax.swing.JLabel();
        jContactNo = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jTextFieldSupplierName = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldContactNo = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonProceed = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonBack1 = new javax.swing.JButton();
        jButtonClear1 = new javax.swing.JButton();
        jButtonViewsupplier = new javax.swing.JButton();
        jButtonAddNewMember = new javax.swing.JButton();
        jButtonViewsupplierinventory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("Supplier");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setText("Add New Supplier");

        jSupplierName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jSupplierName.setText("Supplier Name");

        jSupplierAddress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jSupplierAddress.setText("Address");

        jContactNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jContactNo.setText("Contact No.");

        jEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jEmail.setText("Email");

        jTextFieldSupplierName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupplierNameActionPerformed(evt);
            }
        });

        jTextFieldAddress.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jTextFieldContactNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactNoActionPerformed(evt);
            }
        });

        jTextFieldEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jButtonProceed.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonBack1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack1.setText("Back");
        jButtonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBack1ActionPerformed(evt);
            }
        });

        jButtonClear1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClear1.setText("Clear");
        jButtonClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClear1ActionPerformed(evt);
            }
        });

        jButtonViewsupplier.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewsupplier.setText("View Suppliers");
        jButtonViewsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewsupplierActionPerformed(evt);
            }
        });

        jButtonAddNewMember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddNewMember.setText("Add New Supplier");
        jButtonAddNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewMemberActionPerformed(evt);
            }
        });

        jButtonViewsupplierinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewsupplierinventory.setText("View Supplier-Inventory");
        jButtonViewsupplierinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewsupplierinventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddNewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewsupplierinventory))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonViewsupplierinventory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonAddNewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonViewsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButtonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButtonBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSupplierName)
                                    .addComponent(jSupplierAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jContactNo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonProceed)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonClear)
                                .addGap(20, 20, 20)
                                .addComponent(jButtonBack)))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSupplierName)
                            .addComponent(jTextFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSupplierAddress)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jContactNo)
                            .addComponent(jTextFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonProceed)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonBack))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // Back to Supplier
        new ViewSupplier().setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactNoActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
        // TODO add your handling code here:
        String Supplier_name=jTextFieldSupplierName.getText();
        String Supplier_Address=jTextFieldAddress.getText();
        String Supplier_Contactno=jTextFieldContactNo.getText();
        String Supplier_Email=jTextFieldEmail.getText();
          Connection con= ConnectionProvider.getCon();
           try{
           
           //step3: create sql query and execute it
          String sql="insert into supplier(Supplier_Name,Supplier_Address,Supplier_Contactno,Supplier_Email)values(?,?,?,?)";
           PreparedStatement st=con.prepareStatement(sql);
           st.setString(1, Supplier_name);
           st.setString(2, Supplier_Address);
           st.setString(3, Supplier_Contactno);
           st.setString(4,Supplier_Email);
           st.execute();
          //step4: close the connection
           con.close();
           JOptionPane.showMessageDialog(rootPane, "Sucessfully done");

           }
       catch(Exception ex){
            System.out.println(ex);
}
           try {
            jTextFieldAddress.setText(null);
            jTextFieldContactNo.setText(null);
            jTextFieldEmail.setText(null);
            jTextFieldSupplierName.setText(null);
        } catch (Exception e) {
        }
 
        
    }//GEN-LAST:event_jButtonProceedActionPerformed

    private void jTextFieldSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupplierNameActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
                    jTextFieldAddress.setText(null);
            jTextFieldContactNo.setText(null);
            jTextFieldEmail.setText(null);
            jTextFieldSupplierName.setText(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBack1ActionPerformed
        // TODO add your handling code here:
        new  Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonBack1ActionPerformed

    private void jButtonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClear1ActionPerformed
        // TODO add your handling code here:
        jTextFieldAddress.setText(null);
        jTextFieldContactNo.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldSupplierName.setText(null);
    }//GEN-LAST:event_jButtonClear1ActionPerformed

    private void jButtonViewsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewsupplierActionPerformed
        // TODO add your handling code here:
        new ViewSupplier().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewsupplierActionPerformed

    private void jButtonAddNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewMemberActionPerformed
        // TODO add your handling code here:
        new AddNewSupplier().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonAddNewMemberActionPerformed

    private void jButtonViewsupplierinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewsupplierinventoryActionPerformed
        // TODO add your handling code here:
   new Supplier_inventory().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButtonViewsupplierinventoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNewMember;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBack1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClear1;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonViewsupplier;
    private javax.swing.JButton jButtonViewsupplierinventory;
    private javax.swing.JLabel jContactNo;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jSupplierAddress;
    private javax.swing.JLabel jSupplierName;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldContactNo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldSupplierName;
    // End of variables declaration//GEN-END:variables
}
