/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Account;

import ConnectionProvider.ConnectionProvider;
import Member.ViewMember;
import Report.Report;
import Transaction.Deposit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Viewtransactions extends javax.swing.JFrame {

    /**
     * Creates new form Viewtransactions
     */
    public Viewtransactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransactions = new javax.swing.JTable();
        jTextFieldSearchAccountnum = new javax.swing.JTextField();
        jLabelSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAccountnum = new javax.swing.JTextField();
        jTextFieldAccountname = new javax.swing.JTextField();
        jTextFieldMemberid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelSideBar2 = new javax.swing.JPanel();
        jButtonViewAccount2 = new javax.swing.JButton();
        jButtonCreateaccount2 = new javax.swing.JButton();
        jButtonViewmember2 = new javax.swing.JButton();
        jButtontransactions2 = new javax.swing.JButton();
        jButtonback2 = new javax.swing.JButton();
        jButtonclear2 = new javax.swing.JButton();
        jButtonhome2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableTransactions.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTableTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Date", "Particulars", "Debit Amount", "Credit Amount", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTransactions.setRowHeight(30);
        jTableTransactions.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableTransactions);
        if (jTableTransactions.getColumnModel().getColumnCount() > 0) {
            jTableTransactions.getColumnModel().getColumn(0).setResizable(false);
            jTableTransactions.getColumnModel().getColumn(0).setPreferredWidth(8);
            jTableTransactions.getColumnModel().getColumn(1).setResizable(false);
            jTableTransactions.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTableTransactions.getColumnModel().getColumn(2).setResizable(false);
            jTableTransactions.getColumnModel().getColumn(2).setPreferredWidth(400);
            jTableTransactions.getColumnModel().getColumn(3).setResizable(false);
            jTableTransactions.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTableTransactions.getColumnModel().getColumn(4).setResizable(false);
            jTableTransactions.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTableTransactions.getColumnModel().getColumn(5).setResizable(false);
            jTableTransactions.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextFieldSearchAccountnum.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldSearchAccountnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchAccountnumActionPerformed(evt);
            }
        });
        jTextFieldSearchAccountnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchAccountnumKeyPressed(evt);
            }
        });

        jLabelSearch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSearch.setText("Search");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Account Name");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Account Number");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Member Id");

        jTextFieldAccountnum.setEditable(false);
        jTextFieldAccountnum.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAccountnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountnumActionPerformed(evt);
            }
        });
        jTextFieldAccountnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAccountnumKeyPressed(evt);
            }
        });

        jTextFieldAccountname.setEditable(false);
        jTextFieldAccountname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAccountname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountnameActionPerformed(evt);
            }
        });
        jTextFieldAccountname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAccountnameKeyPressed(evt);
            }
        });

        jTextFieldMemberid.setEditable(false);
        jTextFieldMemberid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMemberid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMemberidActionPerformed(evt);
            }
        });
        jTextFieldMemberid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMemberidKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel4.setText("View Statement");

        jButtonViewAccount2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewAccount2.setText("View Accounts");
        jButtonViewAccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAccount2ActionPerformed(evt);
            }
        });

        jButtonCreateaccount2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateaccount2.setText("Create Account");

        jButtonViewmember2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewmember2.setText("View Members");
        jButtonViewmember2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewmember2ActionPerformed(evt);
            }
        });

        jButtontransactions2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtontransactions2.setText("Transactions");
        jButtontransactions2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontransactions2ActionPerformed(evt);
            }
        });

        jButtonback2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonback2.setText("Back");
        jButtonback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonback2ActionPerformed(evt);
            }
        });

        jButtonclear2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonclear2.setText("Clear");
        jButtonclear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclear2ActionPerformed(evt);
            }
        });

        jButtonhome2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonhome2.setText("Home");
        jButtonhome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhome2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSideBar2Layout = new javax.swing.GroupLayout(jPanelSideBar2);
        jPanelSideBar2.setLayout(jPanelSideBar2Layout);
        jPanelSideBar2Layout.setHorizontalGroup(
            jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBar2Layout.createSequentialGroup()
                .addGroup(jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonViewAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateaccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewmember2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontransactions2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonback2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonhome2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonclear2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelSideBar2Layout.setVerticalGroup(
            jPanelSideBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSideBar2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButtonViewAccount2)
                .addGap(53, 53, 53)
                .addComponent(jButtonCreateaccount2)
                .addGap(39, 39, 39)
                .addComponent(jButtonViewmember2)
                .addGap(40, 40, 40)
                .addComponent(jButtontransactions2)
                .addGap(31, 31, 31)
                .addComponent(jButtonclear2)
                .addGap(19, 19, 19)
                .addComponent(jButtonhome2)
                .addGap(29, 29, 29)
                .addComponent(jButtonback2))
        );

        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanelSideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMemberid)
                            .addComponent(jTextFieldAccountnum)
                            .addComponent(jTextFieldAccountname)
                            .addComponent(jTextFieldSearchAccountnum, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(233, 233, 233)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelSideBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSearchAccountnum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldAccountname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldAccountnum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMemberid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1000, 1000, 1000))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchAccountnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchAccountnumActionPerformed
        // TODO add your handling code here:
            jTableTransactions.setModel(new DefaultTableModel(null,new String [] {
            "Transaction ID", "Date", "Particulars","Debit Amount","Credit Amount","Balance"
        }));
                ResultSet rs;
                int Account_no=Integer.parseInt(jTextFieldSearchAccountnum.getText());
                try{
                     Connection con= ConnectionProvider.getCon();
                    //step3: create sql query and execute it
                    String sql="select * from Transaction where Account_no="+Account_no;
                    PreparedStatement st=con.prepareStatement(sql);
                    rs=st.executeQuery();
                    int Amount_balance=0;
                    while (rs.next()) {

                        String Member_id=String.valueOf(rs.getInt("Member_id"));
                        String Account_num=String.valueOf(rs.getInt("Account_no"));
                        String Account_name=rs.getString("Account_name");
                        String Transactionid=String.valueOf(rs.getInt("Transaction_id"));
                        int Amount_retrived=rs.getInt("Amount");
                        String Amount=String.valueOf(rs.getInt("Amount"));
                        
                        String Particulars=rs.getString("Transacted_by")+" "+rs.getString("Remarks");
                        String Transactiondate=String.valueOf(rs.getDate("datetime"));
                        String Transaction_type=rs.getString("Transaction_type");
                         if (Transaction_type.equalsIgnoreCase("Deposit")) {
                             Amount_balance=Amount_balance+Amount_retrived;
                             String Amount_balancetotable=String.valueOf(Amount_balance);
                        String table_data[]={Transactionid,Transactiondate,Particulars,"",Amount,Amount_balancetotable};
                        DefaultTableModel tablemodel=(DefaultTableModel)jTableTransactions.getModel();
                        tablemodel.addRow(table_data);
                        }
                         else if (Transaction_type.equalsIgnoreCase("Withdraw")) {
                        Amount_balance=Amount_balance-Amount_retrived;
                          String Amount_balancetotable=String.valueOf(Amount_balance);
                        String table_data[]={Transactionid,Transactiondate,Particulars,Amount,"",Amount_balancetotable};
                        DefaultTableModel tablemodel=(DefaultTableModel)jTableTransactions.getModel();
                        tablemodel.addRow(table_data);
                        }


                        jTextFieldAccountname.setText(Account_name);
                        jTextFieldAccountnum.setText(Account_num);
                        jTextFieldMemberid.setText(Member_id);
                       
                    }
                    //step4: close the connection
                    con.close();
                }
                catch(Exception ex){
                    System.out.println(ex);
        
                }
    }//GEN-LAST:event_jTextFieldSearchAccountnumActionPerformed

    private void jTextFieldSearchAccountnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchAccountnumKeyPressed
        // TODO add your handling code here:
               jTableTransactions.setModel(new DefaultTableModel(null,new String [] {
            "Transaction ID", "Date", "Particulars","Debit Amount","Credit Amount","Balance"
        }));

        char c=evt.getKeyChar();
        try {
            if (Character.isDigit(c)||evt.getKeyCode()==KeyEvent.VK_ENTER||
                    evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||
                    evt.getKeyCode()==KeyEvent.VK_DELETE||
                    evt.getKeyCode()==KeyEvent.VK_LEFT||
                    evt.getKeyCode()==KeyEvent.VK_RIGHT||
                    evt.getKeyCode()==KeyEvent.VK_BACK_SPACE||
                    evt.getKeyCode()==KeyEvent.VK_DELETE||
                    evt.getKeyCode()==KeyEvent.VK_LEFT||
                    evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_SPACE) {
                jTextFieldSearchAccountnum.setEditable(true);
            }
            else{
                jTextFieldSearchAccountnum.setEditable(false);
            }
        }
        catch (Exception ex) {

        }
        try {
            if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
               
                ResultSet rs;
                int Account_no=Integer.parseInt(jTextFieldSearchAccountnum.getText());
                try{
                     Connection con= ConnectionProvider.getCon();
                    //step3: create sql query and execute it
                    String sql="select * from Transaction where Account_no="+Account_no;
                    PreparedStatement st=con.prepareStatement(sql);
                    rs=st.executeQuery();
                    int Amount_balance=0;
                    while (rs.next()) {

                        String Member_id=String.valueOf(rs.getInt("Member_id"));
                        String Account_num=String.valueOf(rs.getInt("Account_no"));
                        String Account_name=rs.getString("Account_name");
                        String Transactionid=String.valueOf(rs.getInt("Transaction_id"));
                        int Amount_retrived=rs.getInt("Amount");
                        String Amount=String.valueOf(rs.getInt("Amount"));
                        
                        String Particulars=rs.getString("Transacted_by")+" "+rs.getString("Remarks");
                        String Transactiondate=String.valueOf(rs.getDate("datetime"));
                        String Transaction_type=rs.getString("Transaction_type");
                         if (Transaction_type.equalsIgnoreCase("Deposit")) {
                             Amount_balance=Amount_balance+Amount_retrived;
                             String Amount_balancetotable=String.valueOf(Amount_balance);
                        String table_data[]={Transactionid,Transactiondate,Particulars,"",Amount,Amount_balancetotable};
                        DefaultTableModel tablemodel=(DefaultTableModel)jTableTransactions.getModel();
                        tablemodel.addRow(table_data);
                        }
                         else if (Transaction_type.equalsIgnoreCase("Withdraw")) {
                        Amount_balance=Amount_balance-Amount_retrived;
                          String Amount_balancetotable=String.valueOf(Amount_balance);
                        String table_data[]={Transactionid,Transactiondate,Particulars,Amount,"",Amount_balancetotable};
                        DefaultTableModel tablemodel=(DefaultTableModel)jTableTransactions.getModel();
                        tablemodel.addRow(table_data);
                        }


                        jTextFieldAccountname.setText(Account_name);
                        jTextFieldAccountnum.setText(Account_num);
                        jTextFieldMemberid.setText(Member_id);
                       
                    }
                    //step4: close the connection
                    con.close();
                }
                catch(Exception ex){
                    System.out.println(ex);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextFieldSearchAccountnumKeyPressed

    private void jTextFieldAccountnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountnumActionPerformed

    private void jTextFieldAccountnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccountnumKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountnumKeyPressed

    private void jTextFieldAccountnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountnameActionPerformed

    private void jTextFieldAccountnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccountnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountnameKeyPressed

    private void jTextFieldMemberidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMemberidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMemberidActionPerformed

    private void jTextFieldMemberidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMemberidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMemberidKeyPressed

    private void jButtonViewAccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAccount2ActionPerformed
        // TODO add your handling code here:
        new ViewAccounts().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewAccount2ActionPerformed

    private void jButtonViewmember2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewmember2ActionPerformed
        // TODO add your handling code here:
        new ViewMember().setVisible(true);
    }//GEN-LAST:event_jButtonViewmember2ActionPerformed

    private void jButtonback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonback2ActionPerformed
        // TODO add your handling code here:
     new Report().setVisible(true);
        setVisible(false);
     
    }//GEN-LAST:event_jButtonback2ActionPerformed

    private void jButtonclear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclear2ActionPerformed
        // TODO add your handling code here:
        jTableTransactions.setModel(new DefaultTableModel(null,new String [] {
            "Transaction ID", "Date", "Particulars","Debit Amount","Credit Amount","Balance"
        }));
        jTextFieldAccountname.setText(null);
        jTextFieldAccountnum.setText(null);
        jTextFieldMemberid.setText(null);
        jTextFieldSearchAccountnum.setText(null);
    }//GEN-LAST:event_jButtonclear2ActionPerformed

    private void jButtontransactions2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontransactions2ActionPerformed
        // TODO add your handling code here:
        new Deposit().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtontransactions2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

      String Account_name= jTextFieldAccountname.getText();
       
        MessageFormat header=new MessageFormat("Statement of Account Name:"
                +Account_name);
        MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {
           jTableTransactions.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            
        } catch (Exception e) {
            e.getMessage();
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonhome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhome2ActionPerformed
        // TODO add your handling code here:
        new Home.Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonhome2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewtransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewtransactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCreateaccount2;
    private javax.swing.JButton jButtonViewAccount2;
    private javax.swing.JButton jButtonViewmember2;
    private javax.swing.JButton jButtonback2;
    private javax.swing.JButton jButtonclear2;
    private javax.swing.JButton jButtonhome2;
    private javax.swing.JButton jButtontransactions2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanelSideBar2;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTransactions;
    private javax.swing.JTextField jTextFieldAccountname;
    private javax.swing.JTextField jTextFieldAccountnum;
    private javax.swing.JTextField jTextFieldMemberid;
    private javax.swing.JTextField jTextFieldSearchAccountnum;
    // End of variables declaration//GEN-END:variables
}
