/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryDetails;

import MemberInventory.Member_inventory;
import Home.Home;
import InventoryDetails.AddNewInventory;
import InventoryDetails.Createinventory;
import MemberInventory.Issuetomember;
import SupplierDetails.Supplier_inventory;

/**
 *
 * @author Dell
 */
public class Inventory extends javax.swing.JFrame {

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonIssue = new javax.swing.JButton();
        jButtonViewstock = new javax.swing.JButton();
        jButtonViewMember = new javax.swing.JButton();
        jButtonSupplier = new javax.swing.JButton();
        jButtonAddNew = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jInventoryHead = new javax.swing.JLabel();
        jInventory = new javax.swing.JLabel();
        jButtonCreateinventory = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonIssue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonIssue.setText("Issue Inventory to member");
        jButtonIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIssueActionPerformed(evt);
            }
        });

        jButtonViewstock.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewstock.setText("View Inventory Stock");
        jButtonViewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewstockActionPerformed(evt);
            }
        });

        jButtonViewMember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewMember.setText("View Member-Inventory Details");
        jButtonViewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewMemberActionPerformed(evt);
            }
        });

        jButtonSupplier.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonSupplier.setText("View Supplier-Inventory Details");
        jButtonSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupplierActionPerformed(evt);
            }
        });

        jButtonAddNew.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddNew.setText("Add Inventory");
        jButtonAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jInventoryHead.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jInventoryHead.setText("Pashupati Mahila JibikoParjan Krishi Sahakari Sanstha");

        jInventory.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jInventory.setText("Inventory");

        jButtonCreateinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateinventory.setText("Create New Inventory");
        jButtonCreateinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateinventoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButtonViewMember))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonIssue))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButtonSupplier))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonViewstock, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jButtonCreateinventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jInventory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jInventoryHead))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInventoryHead)
                .addGap(30, 30, 30)
                .addComponent(jInventory)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewstock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCreateinventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonViewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIssueActionPerformed
        // TODO add your handling code here:
        new Issuetomember().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonIssueActionPerformed

    private void jButtonAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewActionPerformed
        // TODO add your handling code here:
        new AddNewInventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonAddNewActionPerformed

    private void jButtonViewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewMemberActionPerformed
        // TODO add your handling code here:
        new Member_inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewMemberActionPerformed

    private void jButtonViewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewstockActionPerformed
        // TODO add your handling code here:
        new ViewInventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewstockActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // Back to home
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonCreateinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateinventoryActionPerformed
        // TODO add your handling code here:
        new Createinventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateinventoryActionPerformed

    private void jButtonSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupplierActionPerformed
        // TODO add your handling code here:
        new Supplier_inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddNew;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCreateinventory;
    private javax.swing.JButton jButtonIssue;
    private javax.swing.JButton jButtonSupplier;
    private javax.swing.JButton jButtonViewMember;
    private javax.swing.JButton jButtonViewstock;
    private javax.swing.JLabel jInventory;
    private javax.swing.JLabel jInventoryHead;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
