/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InventoryDetails;

import ConnectionProvider.ConnectionProvider;
import MemberInventory.Issuetomember;
import Home.Home;
import SupplierDetails.Supplier_inventory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dell
 */
public class ViewInventory extends javax.swing.JFrame {

    /**
     * Creates new form ViewInventory
     */
    public ViewInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelInventoryid = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jTextFieldInventoryid = new javax.swing.JTextField();
        jLabelInventoryname = new javax.swing.JLabel();
        jTextFieldInventoryname = new javax.swing.JTextField();
        jLabelQuantity = new javax.swing.JLabel();
        jTextFieldInventorytype = new javax.swing.JTextField();
        jLabelInventorytype = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jButtonProceed = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonViewinventory = new javax.swing.JButton();
        jButtonCreateinventory = new javax.swing.JButton();
        jButtonAddinventory = new javax.swing.JButton();
        jButtonViewmemberinventory = new javax.swing.JButton();
        jButtonViewsupplierinventory = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonIssuetomember = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInventory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelSearch = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInventoryid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelInventoryid.setText("Inventory ID");

        jTextFieldQuantity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextFieldInventoryid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldInventoryid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInventoryidActionPerformed(evt);
            }
        });

        jLabelInventoryname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelInventoryname.setText("Inventory Name");

        jTextFieldInventoryname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelQuantity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelQuantity.setText("Quantity");

        jTextFieldInventorytype.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabelInventorytype.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelInventorytype.setText("Inventory Type");

        jButtonEdit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonProceed.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCancel.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonProceed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInventoryname)
                            .addComponent(jLabelInventorytype)
                            .addComponent(jLabelQuantity)
                            .addComponent(jLabelInventoryid))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInventoryname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInventoryid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInventorytype, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInventoryid)
                    .addComponent(jTextFieldInventoryid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInventoryname)
                    .addComponent(jTextFieldInventoryname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInventorytype)
                    .addComponent(jTextFieldInventorytype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantity)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonProceed)
                    .addComponent(jButtonCancel))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jButtonViewinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewinventory.setText("View Inventory");
        jButtonViewinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewinventoryActionPerformed(evt);
            }
        });

        jButtonCreateinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonCreateinventory.setText("Create Inventory");
        jButtonCreateinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateinventoryActionPerformed(evt);
            }
        });

        jButtonAddinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonAddinventory.setText("Add Inventory");
        jButtonAddinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddinventoryActionPerformed(evt);
            }
        });

        jButtonViewmemberinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewmemberinventory.setText("View Member-Inventory");

        jButtonViewsupplierinventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonViewsupplierinventory.setText("View Supplier-Inventory");
        jButtonViewsupplierinventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewsupplierinventoryActionPerformed(evt);
            }
        });

        jButtonBack.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonHome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonIssuetomember.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonIssuetomember.setText("Issue To Member");
        jButtonIssuetomember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIssuetomemberActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonViewinventory)
                    .addComponent(jButtonCreateinventory)
                    .addComponent(jButtonAddinventory)
                    .addComponent(jButtonViewmemberinventory)
                    .addComponent(jButtonViewsupplierinventory)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonHome)
                    .addComponent(jButtonIssuetomember)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonViewinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonCreateinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonAddinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonViewmemberinventory)
                .addGap(40, 40, 40)
                .addComponent(jButtonViewsupplierinventory)
                .addGap(38, 38, 38)
                .addComponent(jButtonIssuetomember)
                .addGap(18, 18, 18)
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addGap(29, 29, 29)
                .addComponent(jButtonHome)
                .addGap(33, 33, 33))
        );

        jTableInventory.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTableInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inventory Id", "Inventory Name", "Inventory Type", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableInventory.setAlignmentX(1.0F);
        jTableInventory.setAlignmentY(1.0F);
        jTableInventory.setRowHeight(30);
        jTableInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableInventory);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setText("Inventory");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setText("Inventory Details");

        jLabelSearch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSearch.setText("Search");

        jTextFieldSearch.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(623, 623, 623)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(602, 602, 602)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(565, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInventoryidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInventoryidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInventoryidActionPerformed

    private void jButtonCreateinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateinventoryActionPerformed
        // TODO add your handling code here:
        new Createinventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonCreateinventoryActionPerformed

    private void jButtonAddinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddinventoryActionPerformed
        // TODO add your handling code here:
        new AddNewInventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonAddinventoryActionPerformed

    private void jButtonViewsupplierinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewsupplierinventoryActionPerformed
        // TODO add your handling code here:
        new Supplier_inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonViewsupplierinventoryActionPerformed

    private void jButtonIssuetomemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIssuetomemberActionPerformed
        // TODO add your handling code here:
        new Issuetomember().setVisible(true);
    }//GEN-LAST:event_jButtonIssuetomemberActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new Inventory().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(false);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonViewinventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewinventoryActionPerformed
        //First clear the table 
        jTableInventory.setModel(new DefaultTableModel(null,new String [] {
            "Inventory ID", "Inventory Name", "Inventory Type", "Quantity"
        }));
       
        ResultSet rs;
           try{
           Connection con= ConnectionProvider.getCon();
           //step3: create sql query and execute it
           String sql="select * from inventory";
           PreparedStatement st=con.prepareStatement(sql);
           rs=st.executeQuery();
               while (rs.next()) {                   
                   
               
           String Inventory_id=String.valueOf(rs.getInt("Inventory_id"));
           String Inventory_name=rs.getString("Inventory_name");
           String Inventory_type=rs.getString("Inventory_type");
           String Quantity=String.valueOf(rs.getInt("Quantity"));
           //
           String table_data[]={Inventory_id,Inventory_name,Inventory_type,Quantity};
           DefaultTableModel tablemodel=(DefaultTableModel)jTableInventory.getModel();
           tablemodel.addRow(table_data);
               }
          //step4: close the connection
           con.close();
           }
       catch(Exception ex){
            System.out.println(ex);
}
           jTextFieldInventoryid.setEditable(false);
           jTextFieldInventoryname.setEditable(false);
           jTextFieldInventorytype.setEditable(false);
           jTextFieldQuantity.setEditable(false);
           
    }//GEN-LAST:event_jButtonViewinventoryActionPerformed

    private void jTableInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableInventoryMouseClicked
        // TODO add your handling code here:
         String[] Inventory=new  String[4];
        
                    if (evt.getClickCount() == 2) {
                int row = jTableInventory.getSelectedRow();
//                int column = jTableSupplier.getSelectedColumn();
                        for (int column1 = 0; column1<4 ; column1++) {
                            String data=String.valueOf(jTableInventory.getValueAt(row, column1));
                            Inventory[column1]=data;    
                        }
                     jTextFieldInventoryid.setText(Inventory[0]);
                     jTextFieldInventoryname.setText(Inventory[1]);
                     jTextFieldInventorytype.setText(Inventory[2]);
                     jTextFieldQuantity.setText(Inventory[3]);
               // you can play more here to get that cell value and all
            }
    }//GEN-LAST:event_jTableInventoryMouseClicked

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
        // TODO add your handling code here:
        jTextFieldInventoryname.setEditable(true);
    }//GEN-LAST:event_jButtonEditMouseClicked

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
        // TODO add your handling code here:
        int Inventory_id=Integer.parseInt(jTextFieldInventoryid.getText());
        String Inventory_name=jTextFieldInventoryname.getText();
        String Inventory_type=jTextFieldInventorytype.getText();
        int Quantity=Integer.parseInt(jTextFieldQuantity.getText());
         
           try{
            Connection con= ConnectionProvider.getCon();
           //step3: create sql query and execute it
           String sql="update Inventory set Inventory_name=? where Inventory_id=?";
           PreparedStatement st=con.prepareStatement(sql);
           st.setString(1, Inventory_name);
           st.setInt(2,Inventory_id);
           st.executeUpdate();
           
          //step4: close the connection
           con.close();
           JOptionPane.showMessageDialog(rootPane, "Updated Inventory with Inventory id"+Inventory_id);

           }
       catch(Exception ex){
            System.out.println(ex);
            try {
               jTextFieldInventoryid.setText(null);
               jTextFieldInventoryname.setText(null);
               jTextFieldInventorytype.setText(null);
               jTextFieldInventoryid.setText(null);
           } catch (Exception e) {
           }
}
    }//GEN-LAST:event_jButtonProceedActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTableInventory.setModel(new DefaultTableModel(null,new String [] {
            "Inventory ID", "Inventory Name", "Inventory Type", "Quantity"
        }));
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jTextFieldSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        String search=jTextFieldSearch.getText().toLowerCase();
        DefaultTableModel table=(DefaultTableModel)jTableInventory.getModel();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        jTableInventory.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextFieldSearchKeyReleased

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddinventory;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCreateinventory;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonIssuetomember;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonViewinventory;
    private javax.swing.JButton jButtonViewmemberinventory;
    private javax.swing.JButton jButtonViewsupplierinventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelInventoryid;
    private javax.swing.JLabel jLabelInventoryname;
    private javax.swing.JLabel jLabelInventorytype;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableInventory;
    private javax.swing.JTextField jTextFieldInventoryid;
    private javax.swing.JTextField jTextFieldInventoryname;
    private javax.swing.JTextField jTextFieldInventorytype;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
